/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApproachRouteImport } from './routes/approach'
import { Route as BrandRouteImport } from './routes/brand'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as DiagnosticRouteImport } from './routes/diagnostic'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as GeoRouteImport } from './routes/geo'
import { Route as LlmsFullDottxtRouteImport } from './routes/llms-full[.]txt'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as OffSiteAeoRouteImport } from './routes/off-site-aeo'
import { Route as OgDotpngRouteImport } from './routes/og[.]png'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ProductRouteImport } from './routes/product'
import { Route as RepoActivityDotsvgRouteImport } from './routes/repo-activity[.]svg'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StatusRouteImport } from './routes/status'
import { Route as VisionRouteImport } from './routes/vision'
import { Route as AeoForIndexRouteImport } from './routes/aeo-for/index'
import { Route as AeoForSlugRouteImport } from './routes/aeo-for/$slug'
import { Route as AgentIndexRouteImport } from './routes/agent/index'
import { Route as AgentCompanyRouteImport } from './routes/agent/company'
import { Route as AgentMethodologyRouteImport } from './routes/agent/methodology'
import { Route as AgentPlatformRouteImport } from './routes/agent/platform'
import { Route as AgentResultsRouteImport } from './routes/agent/results'
import { Route as AiSearchIndexRouteImport } from './routes/ai-search/index'
import { Route as AiSearchSlugRouteImport } from './routes/ai-search/$slug'
import { Route as AiVisibilityToolsIndexRouteImport } from './routes/ai-visibility-tools/index'
import { Route as AiVisibilityToolsSlugRouteImport } from './routes/ai-visibility-tools/$slug'
import { Route as ApiOpenapiDotjsonRouteImport } from './routes/api/openapi[.]json'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSplatRouteImport } from './routes/blog/$'
import { Route as BlogRssDotxmlRouteImport } from './routes/blog/rss[.]xml'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as GlossaryIndexRouteImport } from './routes/glossary/index'
import { Route as GlossarySlugRouteImport } from './routes/glossary/$slug'
import { Route as OgStatusDotpngRouteImport } from './routes/og/status[.]png'
import { Route as ZhIndexRouteImport } from './routes/zh/index'
import { Route as ZhApproachRouteImport } from './routes/zh/approach'
import { Route as ZhCompanyRouteImport } from './routes/zh/company'
import { Route as ZhDiagnosticRouteImport } from './routes/zh/diagnostic'
import { Route as ZhGeoRouteImport } from './routes/zh/geo'
import { Route as ZhMethodologyRouteImport } from './routes/zh/methodology'
import { Route as ZhPlatformRouteImport } from './routes/zh/platform'
import { Route as ZhProductRouteImport } from './routes/zh/product'
import { Route as ZhResearchRouteImport } from './routes/zh/research'
import { Route as ZhResultsRouteImport } from './routes/zh/results'
import { Route as AiVisibilityToolsAlternativesIndexRouteImport } from './routes/ai-visibility-tools/alternatives/index'
import { Route as AiVisibilityToolsAlternativesSlugRouteImport } from './routes/ai-visibility-tools/alternatives/$slug'
import { Route as AiVisibilityToolsCategoryIndexRouteImport } from './routes/ai-visibility-tools/category/index'
import { Route as AiVisibilityToolsCategorySlugRouteImport } from './routes/ai-visibility-tools/category/$slug'
import { Route as AiVisibilityToolsCategoryOpenSourceRouteImport } from './routes/ai-visibility-tools/category/open-source'
import { Route as AiVisibilityToolsCompareIndexRouteImport } from './routes/ai-visibility-tools/compare/index'
import { Route as AiVisibilityToolsCompareSlugRouteImport } from './routes/ai-visibility-tools/compare/$slug'
import { Route as AiVisibilityToolsFeaturesIndexRouteImport } from './routes/ai-visibility-tools/features/index'
import { Route as AiVisibilityToolsFeaturesSlugRouteImport } from './routes/ai-visibility-tools/features/$slug'
import { Route as ApiRepoActivityRefreshRouteImport } from './routes/api/repo-activity/refresh'
import { Route as LlmsDotmdxDocsSplatRouteImport } from './routes/llms[.]mdx.docs.$'
import { Route as OgDocsSplatRouteImport } from './routes/og/docs/$'
import { Route as ApiPlausibleEventIndexRouteImport } from './routes/api/plausible/event/index'
import { Route as ApiPlausibleJsScriptIndexRouteImport } from './routes/api/plausible/js/script/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApproachRoute = ApproachRouteImport.update({
  id: '/approach',
  path: '/approach',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandRoute = BrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticRoute = DiagnosticRouteImport.update({
  id: '/diagnostic',
  path: '/diagnostic',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const GeoRoute = GeoRouteImport.update({
  id: '/geo',
  path: '/geo',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsFullDottxtRoute = LlmsFullDottxtRouteImport.update({
  id: '/llms-full.txt',
  path: '/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const OffSiteAeoRoute = OffSiteAeoRouteImport.update({
  id: '/off-site-aeo',
  path: '/off-site-aeo',
  getParentRoute: () => rootRouteImport,
} as any)
const OgDotpngRoute = OgDotpngRouteImport.update({
  id: '/og.png',
  path: '/og.png',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductRoute = ProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => rootRouteImport,
} as any)
const RepoActivityDotsvgRoute = RepoActivityDotsvgRouteImport.update({
  id: '/repo-activity.svg',
  path: '/repo-activity.svg',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const VisionRoute = VisionRouteImport.update({
  id: '/vision',
  path: '/vision',
  getParentRoute: () => rootRouteImport,
} as any)
const AeoForIndexRoute = AeoForIndexRouteImport.update({
  id: '/aeo-for/',
  path: '/aeo-for/',
  getParentRoute: () => rootRouteImport,
} as any)
const AeoForSlugRoute = AeoForSlugRouteImport.update({
  id: '/aeo-for/$slug',
  path: '/aeo-for/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentIndexRoute = AgentIndexRouteImport.update({
  id: '/agent/',
  path: '/agent/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentCompanyRoute = AgentCompanyRouteImport.update({
  id: '/agent/company',
  path: '/agent/company',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentMethodologyRoute = AgentMethodologyRouteImport.update({
  id: '/agent/methodology',
  path: '/agent/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentPlatformRoute = AgentPlatformRouteImport.update({
  id: '/agent/platform',
  path: '/agent/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentResultsRoute = AgentResultsRouteImport.update({
  id: '/agent/results',
  path: '/agent/results',
  getParentRoute: () => rootRouteImport,
} as any)
const AiSearchIndexRoute = AiSearchIndexRouteImport.update({
  id: '/ai-search/',
  path: '/ai-search/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiSearchSlugRoute = AiSearchSlugRouteImport.update({
  id: '/ai-search/$slug',
  path: '/ai-search/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AiVisibilityToolsIndexRoute = AiVisibilityToolsIndexRouteImport.update({
  id: '/ai-visibility-tools/',
  path: '/ai-visibility-tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiVisibilityToolsSlugRoute = AiVisibilityToolsSlugRouteImport.update({
  id: '/ai-visibility-tools/$slug',
  path: '/ai-visibility-tools/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenapiDotjsonRoute = ApiOpenapiDotjsonRouteImport.update({
  id: '/api/openapi.json',
  path: '/api/openapi.json',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSplatRoute = BlogSplatRouteImport.update({
  id: '/blog/$',
  path: '/blog/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRssDotxmlRoute = BlogRssDotxmlRouteImport.update({
  id: '/blog/rss.xml',
  path: '/blog/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryIndexRoute = GlossaryIndexRouteImport.update({
  id: '/glossary/',
  path: '/glossary/',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossarySlugRoute = GlossarySlugRouteImport.update({
  id: '/glossary/$slug',
  path: '/glossary/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OgStatusDotpngRoute = OgStatusDotpngRouteImport.update({
  id: '/og/status.png',
  path: '/og/status.png',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhIndexRoute = ZhIndexRouteImport.update({
  id: '/zh/',
  path: '/zh/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhApproachRoute = ZhApproachRouteImport.update({
  id: '/zh/approach',
  path: '/zh/approach',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhCompanyRoute = ZhCompanyRouteImport.update({
  id: '/zh/company',
  path: '/zh/company',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhDiagnosticRoute = ZhDiagnosticRouteImport.update({
  id: '/zh/diagnostic',
  path: '/zh/diagnostic',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhGeoRoute = ZhGeoRouteImport.update({
  id: '/zh/geo',
  path: '/zh/geo',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhMethodologyRoute = ZhMethodologyRouteImport.update({
  id: '/zh/methodology',
  path: '/zh/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhPlatformRoute = ZhPlatformRouteImport.update({
  id: '/zh/platform',
  path: '/zh/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhProductRoute = ZhProductRouteImport.update({
  id: '/zh/product',
  path: '/zh/product',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhResearchRoute = ZhResearchRouteImport.update({
  id: '/zh/research',
  path: '/zh/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhResultsRoute = ZhResultsRouteImport.update({
  id: '/zh/results',
  path: '/zh/results',
  getParentRoute: () => rootRouteImport,
} as any)
const AiVisibilityToolsAlternativesIndexRoute =
  AiVisibilityToolsAlternativesIndexRouteImport.update({
    id: '/ai-visibility-tools/alternatives/',
    path: '/ai-visibility-tools/alternatives/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AiVisibilityToolsAlternativesSlugRoute =
  AiVisibilityToolsAlternativesSlugRouteImport.update({
    id: '/ai-visibility-tools/alternatives/$slug',
    path: '/ai-visibility-tools/alternatives/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const AiVisibilityToolsCategoryIndexRoute =
  AiVisibilityToolsCategoryIndexRouteImport.update({
    id: '/ai-visibility-tools/category/',
    path: '/ai-visibility-tools/category/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AiVisibilityToolsCategorySlugRoute =
  AiVisibilityToolsCategorySlugRouteImport.update({
    id: '/ai-visibility-tools/category/$slug',
    path: '/ai-visibility-tools/category/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const AiVisibilityToolsCategoryOpenSourceRoute =
  AiVisibilityToolsCategoryOpenSourceRouteImport.update({
    id: '/ai-visibility-tools/category/open-source',
    path: '/ai-visibility-tools/category/open-source',
    getParentRoute: () => rootRouteImport,
  } as any)
const AiVisibilityToolsCompareIndexRoute =
  AiVisibilityToolsCompareIndexRouteImport.update({
    id: '/ai-visibility-tools/compare/',
    path: '/ai-visibility-tools/compare/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AiVisibilityToolsCompareSlugRoute =
  AiVisibilityToolsCompareSlugRouteImport.update({
    id: '/ai-visibility-tools/compare/$slug',
    path: '/ai-visibility-tools/compare/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const AiVisibilityToolsFeaturesIndexRoute =
  AiVisibilityToolsFeaturesIndexRouteImport.update({
    id: '/ai-visibility-tools/features/',
    path: '/ai-visibility-tools/features/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AiVisibilityToolsFeaturesSlugRoute =
  AiVisibilityToolsFeaturesSlugRouteImport.update({
    id: '/ai-visibility-tools/features/$slug',
    path: '/ai-visibility-tools/features/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiRepoActivityRefreshRoute = ApiRepoActivityRefreshRouteImport.update({
  id: '/api/repo-activity/refresh',
  path: '/api/repo-activity/refresh',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDotmdxDocsSplatRoute = LlmsDotmdxDocsSplatRouteImport.update({
  id: '/llms.mdx/docs/$',
  path: '/llms.mdx/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const OgDocsSplatRoute = OgDocsSplatRouteImport.update({
  id: '/og/docs/$',
  path: '/og/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlausibleEventIndexRoute = ApiPlausibleEventIndexRouteImport.update({
  id: '/api/plausible/event/',
  path: '/api/plausible/event/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlausibleJsScriptIndexRoute =
  ApiPlausibleJsScriptIndexRouteImport.update({
    id: '/api/plausible/js/script/',
    path: '/api/plausible/js/script/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/approach': typeof ApproachRoute
  '/brand': typeof BrandRoute
  '/changelog': typeof ChangelogRoute
  '/company': typeof CompanyRoute
  '/diagnostic': typeof DiagnosticRoute
  '/features': typeof FeaturesRoute
  '/geo': typeof GeoRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/methodology': typeof MethodologyRoute
  '/off-site-aeo': typeof OffSiteAeoRoute
  '/og.png': typeof OgDotpngRoute
  '/platform': typeof PlatformRoute
  '/pricing': typeof PricingRoute
  '/product': typeof ProductRoute
  '/repo-activity.svg': typeof RepoActivityDotsvgRoute
  '/research': typeof ResearchRoute
  '/results': typeof ResultsRoute
  '/roadmap': typeof RoadmapRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/status': typeof StatusRoute
  '/vision': typeof VisionRoute
  '/aeo-for/$slug': typeof AeoForSlugRoute
  '/agent/company': typeof AgentCompanyRoute
  '/agent/methodology': typeof AgentMethodologyRoute
  '/agent/platform': typeof AgentPlatformRoute
  '/agent/results': typeof AgentResultsRoute
  '/ai-search/$slug': typeof AiSearchSlugRoute
  '/ai-visibility-tools/$slug': typeof AiVisibilityToolsSlugRoute
  '/api/openapi.json': typeof ApiOpenapiDotjsonRoute
  '/api/search': typeof ApiSearchRoute
  '/blog/$': typeof BlogSplatRoute
  '/blog/rss.xml': typeof BlogRssDotxmlRoute
  '/docs/$': typeof DocsSplatRoute
  '/glossary/$slug': typeof GlossarySlugRoute
  '/og/status.png': typeof OgStatusDotpngRoute
  '/zh/approach': typeof ZhApproachRoute
  '/zh/company': typeof ZhCompanyRoute
  '/zh/diagnostic': typeof ZhDiagnosticRoute
  '/zh/geo': typeof ZhGeoRoute
  '/zh/methodology': typeof ZhMethodologyRoute
  '/zh/platform': typeof ZhPlatformRoute
  '/zh/product': typeof ZhProductRoute
  '/zh/research': typeof ZhResearchRoute
  '/zh/results': typeof ZhResultsRoute
  '/aeo-for/': typeof AeoForIndexRoute
  '/agent/': typeof AgentIndexRoute
  '/ai-search/': typeof AiSearchIndexRoute
  '/ai-visibility-tools/': typeof AiVisibilityToolsIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/glossary/': typeof GlossaryIndexRoute
  '/zh/': typeof ZhIndexRoute
  '/ai-visibility-tools/alternatives/$slug': typeof AiVisibilityToolsAlternativesSlugRoute
  '/ai-visibility-tools/category/$slug': typeof AiVisibilityToolsCategorySlugRoute
  '/ai-visibility-tools/category/open-source': typeof AiVisibilityToolsCategoryOpenSourceRoute
  '/ai-visibility-tools/compare/$slug': typeof AiVisibilityToolsCompareSlugRoute
  '/ai-visibility-tools/features/$slug': typeof AiVisibilityToolsFeaturesSlugRoute
  '/api/repo-activity/refresh': typeof ApiRepoActivityRefreshRoute
  '/llms.mdx/docs/$': typeof LlmsDotmdxDocsSplatRoute
  '/og/docs/$': typeof OgDocsSplatRoute
  '/ai-visibility-tools/alternatives/': typeof AiVisibilityToolsAlternativesIndexRoute
  '/ai-visibility-tools/category/': typeof AiVisibilityToolsCategoryIndexRoute
  '/ai-visibility-tools/compare/': typeof AiVisibilityToolsCompareIndexRoute
  '/ai-visibility-tools/features/': typeof AiVisibilityToolsFeaturesIndexRoute
  '/api/plausible/event/': typeof ApiPlausibleEventIndexRoute
  '/api/plausible/js/script/': typeof ApiPlausibleJsScriptIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approach': typeof ApproachRoute
  '/brand': typeof BrandRoute
  '/changelog': typeof ChangelogRoute
  '/company': typeof CompanyRoute
  '/diagnostic': typeof DiagnosticRoute
  '/features': typeof FeaturesRoute
  '/geo': typeof GeoRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/methodology': typeof MethodologyRoute
  '/off-site-aeo': typeof OffSiteAeoRoute
  '/og.png': typeof OgDotpngRoute
  '/platform': typeof PlatformRoute
  '/pricing': typeof PricingRoute
  '/product': typeof ProductRoute
  '/repo-activity.svg': typeof RepoActivityDotsvgRoute
  '/research': typeof ResearchRoute
  '/results': typeof ResultsRoute
  '/roadmap': typeof RoadmapRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/status': typeof StatusRoute
  '/vision': typeof VisionRoute
  '/aeo-for/$slug': typeof AeoForSlugRoute
  '/agent/company': typeof AgentCompanyRoute
  '/agent/methodology': typeof AgentMethodologyRoute
  '/agent/platform': typeof AgentPlatformRoute
  '/agent/results': typeof AgentResultsRoute
  '/ai-search/$slug': typeof AiSearchSlugRoute
  '/ai-visibility-tools/$slug': typeof AiVisibilityToolsSlugRoute
  '/api/openapi.json': typeof ApiOpenapiDotjsonRoute
  '/api/search': typeof ApiSearchRoute
  '/blog/$': typeof BlogSplatRoute
  '/blog/rss.xml': typeof BlogRssDotxmlRoute
  '/docs/$': typeof DocsSplatRoute
  '/glossary/$slug': typeof GlossarySlugRoute
  '/og/status.png': typeof OgStatusDotpngRoute
  '/zh/approach': typeof ZhApproachRoute
  '/zh/company': typeof ZhCompanyRoute
  '/zh/diagnostic': typeof ZhDiagnosticRoute
  '/zh/geo': typeof ZhGeoRoute
  '/zh/methodology': typeof ZhMethodologyRoute
  '/zh/platform': typeof ZhPlatformRoute
  '/zh/product': typeof ZhProductRoute
  '/zh/research': typeof ZhResearchRoute
  '/zh/results': typeof ZhResultsRoute
  '/aeo-for': typeof AeoForIndexRoute
  '/agent': typeof AgentIndexRoute
  '/ai-search': typeof AiSearchIndexRoute
  '/ai-visibility-tools': typeof AiVisibilityToolsIndexRoute
  '/blog': typeof BlogIndexRoute
  '/docs': typeof DocsIndexRoute
  '/glossary': typeof GlossaryIndexRoute
  '/zh': typeof ZhIndexRoute
  '/ai-visibility-tools/alternatives/$slug': typeof AiVisibilityToolsAlternativesSlugRoute
  '/ai-visibility-tools/category/$slug': typeof AiVisibilityToolsCategorySlugRoute
  '/ai-visibility-tools/category/open-source': typeof AiVisibilityToolsCategoryOpenSourceRoute
  '/ai-visibility-tools/compare/$slug': typeof AiVisibilityToolsCompareSlugRoute
  '/ai-visibility-tools/features/$slug': typeof AiVisibilityToolsFeaturesSlugRoute
  '/api/repo-activity/refresh': typeof ApiRepoActivityRefreshRoute
  '/llms.mdx/docs/$': typeof LlmsDotmdxDocsSplatRoute
  '/og/docs/$': typeof OgDocsSplatRoute
  '/ai-visibility-tools/alternatives': typeof AiVisibilityToolsAlternativesIndexRoute
  '/ai-visibility-tools/category': typeof AiVisibilityToolsCategoryIndexRoute
  '/ai-visibility-tools/compare': typeof AiVisibilityToolsCompareIndexRoute
  '/ai-visibility-tools/features': typeof AiVisibilityToolsFeaturesIndexRoute
  '/api/plausible/event': typeof ApiPlausibleEventIndexRoute
  '/api/plausible/js/script': typeof ApiPlausibleJsScriptIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/approach': typeof ApproachRoute
  '/brand': typeof BrandRoute
  '/changelog': typeof ChangelogRoute
  '/company': typeof CompanyRoute
  '/diagnostic': typeof DiagnosticRoute
  '/features': typeof FeaturesRoute
  '/geo': typeof GeoRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/methodology': typeof MethodologyRoute
  '/off-site-aeo': typeof OffSiteAeoRoute
  '/og.png': typeof OgDotpngRoute
  '/platform': typeof PlatformRoute
  '/pricing': typeof PricingRoute
  '/product': typeof ProductRoute
  '/repo-activity.svg': typeof RepoActivityDotsvgRoute
  '/research': typeof ResearchRoute
  '/results': typeof ResultsRoute
  '/roadmap': typeof RoadmapRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/status': typeof StatusRoute
  '/vision': typeof VisionRoute
  '/aeo-for/$slug': typeof AeoForSlugRoute
  '/agent/company': typeof AgentCompanyRoute
  '/agent/methodology': typeof AgentMethodologyRoute
  '/agent/platform': typeof AgentPlatformRoute
  '/agent/results': typeof AgentResultsRoute
  '/ai-search/$slug': typeof AiSearchSlugRoute
  '/ai-visibility-tools/$slug': typeof AiVisibilityToolsSlugRoute
  '/api/openapi.json': typeof ApiOpenapiDotjsonRoute
  '/api/search': typeof ApiSearchRoute
  '/blog/$': typeof BlogSplatRoute
  '/blog/rss.xml': typeof BlogRssDotxmlRoute
  '/docs/$': typeof DocsSplatRoute
  '/glossary/$slug': typeof GlossarySlugRoute
  '/og/status.png': typeof OgStatusDotpngRoute
  '/zh/approach': typeof ZhApproachRoute
  '/zh/company': typeof ZhCompanyRoute
  '/zh/diagnostic': typeof ZhDiagnosticRoute
  '/zh/geo': typeof ZhGeoRoute
  '/zh/methodology': typeof ZhMethodologyRoute
  '/zh/platform': typeof ZhPlatformRoute
  '/zh/product': typeof ZhProductRoute
  '/zh/research': typeof ZhResearchRoute
  '/zh/results': typeof ZhResultsRoute
  '/aeo-for/': typeof AeoForIndexRoute
  '/agent/': typeof AgentIndexRoute
  '/ai-search/': typeof AiSearchIndexRoute
  '/ai-visibility-tools/': typeof AiVisibilityToolsIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/glossary/': typeof GlossaryIndexRoute
  '/zh/': typeof ZhIndexRoute
  '/ai-visibility-tools/alternatives/$slug': typeof AiVisibilityToolsAlternativesSlugRoute
  '/ai-visibility-tools/category/$slug': typeof AiVisibilityToolsCategorySlugRoute
  '/ai-visibility-tools/category/open-source': typeof AiVisibilityToolsCategoryOpenSourceRoute
  '/ai-visibility-tools/compare/$slug': typeof AiVisibilityToolsCompareSlugRoute
  '/ai-visibility-tools/features/$slug': typeof AiVisibilityToolsFeaturesSlugRoute
  '/api/repo-activity/refresh': typeof ApiRepoActivityRefreshRoute
  '/llms.mdx/docs/$': typeof LlmsDotmdxDocsSplatRoute
  '/og/docs/$': typeof OgDocsSplatRoute
  '/ai-visibility-tools/alternatives/': typeof AiVisibilityToolsAlternativesIndexRoute
  '/ai-visibility-tools/category/': typeof AiVisibilityToolsCategoryIndexRoute
  '/ai-visibility-tools/compare/': typeof AiVisibilityToolsCompareIndexRoute
  '/ai-visibility-tools/features/': typeof AiVisibilityToolsFeaturesIndexRoute
  '/api/plausible/event/': typeof ApiPlausibleEventIndexRoute
  '/api/plausible/js/script/': typeof ApiPlausibleJsScriptIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/approach'
    | '/brand'
    | '/changelog'
    | '/company'
    | '/diagnostic'
    | '/features'
    | '/geo'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/methodology'
    | '/off-site-aeo'
    | '/og.png'
    | '/platform'
    | '/pricing'
    | '/product'
    | '/repo-activity.svg'
    | '/research'
    | '/results'
    | '/roadmap'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/status'
    | '/vision'
    | '/aeo-for/$slug'
    | '/agent/company'
    | '/agent/methodology'
    | '/agent/platform'
    | '/agent/results'
    | '/ai-search/$slug'
    | '/ai-visibility-tools/$slug'
    | '/api/openapi.json'
    | '/api/search'
    | '/blog/$'
    | '/blog/rss.xml'
    | '/docs/$'
    | '/glossary/$slug'
    | '/og/status.png'
    | '/zh/approach'
    | '/zh/company'
    | '/zh/diagnostic'
    | '/zh/geo'
    | '/zh/methodology'
    | '/zh/platform'
    | '/zh/product'
    | '/zh/research'
    | '/zh/results'
    | '/aeo-for/'
    | '/agent/'
    | '/ai-search/'
    | '/ai-visibility-tools/'
    | '/blog/'
    | '/docs/'
    | '/glossary/'
    | '/zh/'
    | '/ai-visibility-tools/alternatives/$slug'
    | '/ai-visibility-tools/category/$slug'
    | '/ai-visibility-tools/category/open-source'
    | '/ai-visibility-tools/compare/$slug'
    | '/ai-visibility-tools/features/$slug'
    | '/api/repo-activity/refresh'
    | '/llms.mdx/docs/$'
    | '/og/docs/$'
    | '/ai-visibility-tools/alternatives/'
    | '/ai-visibility-tools/category/'
    | '/ai-visibility-tools/compare/'
    | '/ai-visibility-tools/features/'
    | '/api/plausible/event/'
    | '/api/plausible/js/script/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/approach'
    | '/brand'
    | '/changelog'
    | '/company'
    | '/diagnostic'
    | '/features'
    | '/geo'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/methodology'
    | '/off-site-aeo'
    | '/og.png'
    | '/platform'
    | '/pricing'
    | '/product'
    | '/repo-activity.svg'
    | '/research'
    | '/results'
    | '/roadmap'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/status'
    | '/vision'
    | '/aeo-for/$slug'
    | '/agent/company'
    | '/agent/methodology'
    | '/agent/platform'
    | '/agent/results'
    | '/ai-search/$slug'
    | '/ai-visibility-tools/$slug'
    | '/api/openapi.json'
    | '/api/search'
    | '/blog/$'
    | '/blog/rss.xml'
    | '/docs/$'
    | '/glossary/$slug'
    | '/og/status.png'
    | '/zh/approach'
    | '/zh/company'
    | '/zh/diagnostic'
    | '/zh/geo'
    | '/zh/methodology'
    | '/zh/platform'
    | '/zh/product'
    | '/zh/research'
    | '/zh/results'
    | '/aeo-for'
    | '/agent'
    | '/ai-search'
    | '/ai-visibility-tools'
    | '/blog'
    | '/docs'
    | '/glossary'
    | '/zh'
    | '/ai-visibility-tools/alternatives/$slug'
    | '/ai-visibility-tools/category/$slug'
    | '/ai-visibility-tools/category/open-source'
    | '/ai-visibility-tools/compare/$slug'
    | '/ai-visibility-tools/features/$slug'
    | '/api/repo-activity/refresh'
    | '/llms.mdx/docs/$'
    | '/og/docs/$'
    | '/ai-visibility-tools/alternatives'
    | '/ai-visibility-tools/category'
    | '/ai-visibility-tools/compare'
    | '/ai-visibility-tools/features'
    | '/api/plausible/event'
    | '/api/plausible/js/script'
  id:
    | '__root__'
    | '/'
    | '/approach'
    | '/brand'
    | '/changelog'
    | '/company'
    | '/diagnostic'
    | '/features'
    | '/geo'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/methodology'
    | '/off-site-aeo'
    | '/og.png'
    | '/platform'
    | '/pricing'
    | '/product'
    | '/repo-activity.svg'
    | '/research'
    | '/results'
    | '/roadmap'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/status'
    | '/vision'
    | '/aeo-for/$slug'
    | '/agent/company'
    | '/agent/methodology'
    | '/agent/platform'
    | '/agent/results'
    | '/ai-search/$slug'
    | '/ai-visibility-tools/$slug'
    | '/api/openapi.json'
    | '/api/search'
    | '/blog/$'
    | '/blog/rss.xml'
    | '/docs/$'
    | '/glossary/$slug'
    | '/og/status.png'
    | '/zh/approach'
    | '/zh/company'
    | '/zh/diagnostic'
    | '/zh/geo'
    | '/zh/methodology'
    | '/zh/platform'
    | '/zh/product'
    | '/zh/research'
    | '/zh/results'
    | '/aeo-for/'
    | '/agent/'
    | '/ai-search/'
    | '/ai-visibility-tools/'
    | '/blog/'
    | '/docs/'
    | '/glossary/'
    | '/zh/'
    | '/ai-visibility-tools/alternatives/$slug'
    | '/ai-visibility-tools/category/$slug'
    | '/ai-visibility-tools/category/open-source'
    | '/ai-visibility-tools/compare/$slug'
    | '/ai-visibility-tools/features/$slug'
    | '/api/repo-activity/refresh'
    | '/llms.mdx/docs/$'
    | '/og/docs/$'
    | '/ai-visibility-tools/alternatives/'
    | '/ai-visibility-tools/category/'
    | '/ai-visibility-tools/compare/'
    | '/ai-visibility-tools/features/'
    | '/api/plausible/event/'
    | '/api/plausible/js/script/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApproachRoute: typeof ApproachRoute
  BrandRoute: typeof BrandRoute
  ChangelogRoute: typeof ChangelogRoute
  CompanyRoute: typeof CompanyRoute
  DiagnosticRoute: typeof DiagnosticRoute
  FeaturesRoute: typeof FeaturesRoute
  GeoRoute: typeof GeoRoute
  LlmsFullDottxtRoute: typeof LlmsFullDottxtRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  MethodologyRoute: typeof MethodologyRoute
  OffSiteAeoRoute: typeof OffSiteAeoRoute
  OgDotpngRoute: typeof OgDotpngRoute
  PlatformRoute: typeof PlatformRoute
  PricingRoute: typeof PricingRoute
  ProductRoute: typeof ProductRoute
  RepoActivityDotsvgRoute: typeof RepoActivityDotsvgRoute
  ResearchRoute: typeof ResearchRoute
  ResultsRoute: typeof ResultsRoute
  RoadmapRoute: typeof RoadmapRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StatusRoute: typeof StatusRoute
  VisionRoute: typeof VisionRoute
  AeoForSlugRoute: typeof AeoForSlugRoute
  AgentCompanyRoute: typeof AgentCompanyRoute
  AgentMethodologyRoute: typeof AgentMethodologyRoute
  AgentPlatformRoute: typeof AgentPlatformRoute
  AgentResultsRoute: typeof AgentResultsRoute
  AiSearchSlugRoute: typeof AiSearchSlugRoute
  AiVisibilityToolsSlugRoute: typeof AiVisibilityToolsSlugRoute
  ApiOpenapiDotjsonRoute: typeof ApiOpenapiDotjsonRoute
  ApiSearchRoute: typeof ApiSearchRoute
  BlogSplatRoute: typeof BlogSplatRoute
  BlogRssDotxmlRoute: typeof BlogRssDotxmlRoute
  DocsSplatRoute: typeof DocsSplatRoute
  GlossarySlugRoute: typeof GlossarySlugRoute
  OgStatusDotpngRoute: typeof OgStatusDotpngRoute
  ZhApproachRoute: typeof ZhApproachRoute
  ZhCompanyRoute: typeof ZhCompanyRoute
  ZhDiagnosticRoute: typeof ZhDiagnosticRoute
  ZhGeoRoute: typeof ZhGeoRoute
  ZhMethodologyRoute: typeof ZhMethodologyRoute
  ZhPlatformRoute: typeof ZhPlatformRoute
  ZhProductRoute: typeof ZhProductRoute
  ZhResearchRoute: typeof ZhResearchRoute
  ZhResultsRoute: typeof ZhResultsRoute
  AeoForIndexRoute: typeof AeoForIndexRoute
  AgentIndexRoute: typeof AgentIndexRoute
  AiSearchIndexRoute: typeof AiSearchIndexRoute
  AiVisibilityToolsIndexRoute: typeof AiVisibilityToolsIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  DocsIndexRoute: typeof DocsIndexRoute
  GlossaryIndexRoute: typeof GlossaryIndexRoute
  ZhIndexRoute: typeof ZhIndexRoute
  AiVisibilityToolsAlternativesSlugRoute: typeof AiVisibilityToolsAlternativesSlugRoute
  AiVisibilityToolsCategorySlugRoute: typeof AiVisibilityToolsCategorySlugRoute
  AiVisibilityToolsCategoryOpenSourceRoute: typeof AiVisibilityToolsCategoryOpenSourceRoute
  AiVisibilityToolsCompareSlugRoute: typeof AiVisibilityToolsCompareSlugRoute
  AiVisibilityToolsFeaturesSlugRoute: typeof AiVisibilityToolsFeaturesSlugRoute
  ApiRepoActivityRefreshRoute: typeof ApiRepoActivityRefreshRoute
  LlmsDotmdxDocsSplatRoute: typeof LlmsDotmdxDocsSplatRoute
  OgDocsSplatRoute: typeof OgDocsSplatRoute
  AiVisibilityToolsAlternativesIndexRoute: typeof AiVisibilityToolsAlternativesIndexRoute
  AiVisibilityToolsCategoryIndexRoute: typeof AiVisibilityToolsCategoryIndexRoute
  AiVisibilityToolsCompareIndexRoute: typeof AiVisibilityToolsCompareIndexRoute
  AiVisibilityToolsFeaturesIndexRoute: typeof AiVisibilityToolsFeaturesIndexRoute
  ApiPlausibleEventIndexRoute: typeof ApiPlausibleEventIndexRoute
  ApiPlausibleJsScriptIndexRoute: typeof ApiPlausibleJsScriptIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approach': {
      id: '/approach'
      path: '/approach'
      fullPath: '/approach'
      preLoaderRoute: typeof ApproachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand': {
      id: '/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof BrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostic': {
      id: '/diagnostic'
      path: '/diagnostic'
      fullPath: '/diagnostic'
      preLoaderRoute: typeof DiagnosticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geo': {
      id: '/geo'
      path: '/geo'
      fullPath: '/geo'
      preLoaderRoute: typeof GeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms-full.txt': {
      id: '/llms-full.txt'
      path: '/llms-full.txt'
      fullPath: '/llms-full.txt'
      preLoaderRoute: typeof LlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/off-site-aeo': {
      id: '/off-site-aeo'
      path: '/off-site-aeo'
      fullPath: '/off-site-aeo'
      preLoaderRoute: typeof OffSiteAeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og.png': {
      id: '/og.png'
      path: '/og.png'
      fullPath: '/og.png'
      preLoaderRoute: typeof OgDotpngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product': {
      id: '/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repo-activity.svg': {
      id: '/repo-activity.svg'
      path: '/repo-activity.svg'
      fullPath: '/repo-activity.svg'
      preLoaderRoute: typeof RepoActivityDotsvgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vision': {
      id: '/vision'
      path: '/vision'
      fullPath: '/vision'
      preLoaderRoute: typeof VisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aeo-for/': {
      id: '/aeo-for/'
      path: '/aeo-for'
      fullPath: '/aeo-for/'
      preLoaderRoute: typeof AeoForIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aeo-for/$slug': {
      id: '/aeo-for/$slug'
      path: '/aeo-for/$slug'
      fullPath: '/aeo-for/$slug'
      preLoaderRoute: typeof AeoForSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/': {
      id: '/agent/'
      path: '/agent'
      fullPath: '/agent/'
      preLoaderRoute: typeof AgentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/company': {
      id: '/agent/company'
      path: '/agent/company'
      fullPath: '/agent/company'
      preLoaderRoute: typeof AgentCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/methodology': {
      id: '/agent/methodology'
      path: '/agent/methodology'
      fullPath: '/agent/methodology'
      preLoaderRoute: typeof AgentMethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/platform': {
      id: '/agent/platform'
      path: '/agent/platform'
      fullPath: '/agent/platform'
      preLoaderRoute: typeof AgentPlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/results': {
      id: '/agent/results'
      path: '/agent/results'
      fullPath: '/agent/results'
      preLoaderRoute: typeof AgentResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-search/': {
      id: '/ai-search/'
      path: '/ai-search'
      fullPath: '/ai-search/'
      preLoaderRoute: typeof AiSearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-search/$slug': {
      id: '/ai-search/$slug'
      path: '/ai-search/$slug'
      fullPath: '/ai-search/$slug'
      preLoaderRoute: typeof AiSearchSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-visibility-tools/': {
      id: '/ai-visibility-tools/'
      path: '/ai-visibility-tools'
      fullPath: '/ai-visibility-tools/'
      preLoaderRoute: typeof AiVisibilityToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-visibility-tools/$slug': {
      id: '/ai-visibility-tools/$slug'
      path: '/ai-visibility-tools/$slug'
      fullPath: '/ai-visibility-tools/$slug'
      preLoaderRoute: typeof AiVisibilityToolsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openapi.json': {
      id: '/api/openapi.json'
      path: '/api/openapi.json'
      fullPath: '/api/openapi.json'
      preLoaderRoute: typeof ApiOpenapiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$': {
      id: '/blog/$'
      path: '/blog/$'
      fullPath: '/blog/$'
      preLoaderRoute: typeof BlogSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/rss.xml': {
      id: '/blog/rss.xml'
      path: '/blog/rss.xml'
      fullPath: '/blog/rss.xml'
      preLoaderRoute: typeof BlogRssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary/': {
      id: '/glossary/'
      path: '/glossary'
      fullPath: '/glossary/'
      preLoaderRoute: typeof GlossaryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary/$slug': {
      id: '/glossary/$slug'
      path: '/glossary/$slug'
      fullPath: '/glossary/$slug'
      preLoaderRoute: typeof GlossarySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og/status.png': {
      id: '/og/status.png'
      path: '/og/status.png'
      fullPath: '/og/status.png'
      preLoaderRoute: typeof OgStatusDotpngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/': {
      id: '/zh/'
      path: '/zh'
      fullPath: '/zh/'
      preLoaderRoute: typeof ZhIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/approach': {
      id: '/zh/approach'
      path: '/zh/approach'
      fullPath: '/zh/approach'
      preLoaderRoute: typeof ZhApproachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/company': {
      id: '/zh/company'
      path: '/zh/company'
      fullPath: '/zh/company'
      preLoaderRoute: typeof ZhCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/diagnostic': {
      id: '/zh/diagnostic'
      path: '/zh/diagnostic'
      fullPath: '/zh/diagnostic'
      preLoaderRoute: typeof ZhDiagnosticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/geo': {
      id: '/zh/geo'
      path: '/zh/geo'
      fullPath: '/zh/geo'
      preLoaderRoute: typeof ZhGeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/methodology': {
      id: '/zh/methodology'
      path: '/zh/methodology'
      fullPath: '/zh/methodology'
      preLoaderRoute: typeof ZhMethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/platform': {
      id: '/zh/platform'
      path: '/zh/platform'
      fullPath: '/zh/platform'
      preLoaderRoute: typeof ZhPlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/product': {
      id: '/zh/product'
      path: '/zh/product'
      fullPath: '/zh/product'
      preLoaderRoute: typeof ZhProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/research': {
      id: '/zh/research'
      path: '/zh/research'
      fullPath: '/zh/research'
      preLoaderRoute: typeof ZhResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/results': {
      id: '/zh/results'
      path: '/zh/results'
      fullPath: '/zh/results'
      preLoaderRoute: typeof ZhResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-visibility-tools/alternatives/': {
      id: '/ai-visibility-tools/alternatives/'
      path: '/ai-visibility-tools/alternatives'
      fullPath: '/ai-visibility-tools/alternatives/'
      preLoaderRoute: typeof AiVisibilityToolsAlternativesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-visibility-tools/alternatives/$slug': {
      id: '/ai-visibility-tools/alternatives/$slug'
      path: '/ai-visibility-tools/alternatives/$slug'
      fullPath: '/ai-visibility-tools/alternatives/$slug'
      preLoaderRoute: typeof AiVisibilityToolsAlternativesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-visibility-tools/category/': {
      id: '/ai-visibility-tools/category/'
      path: '/ai-visibility-tools/category'
      fullPath: '/ai-visibility-tools/category/'
      preLoaderRoute: typeof AiVisibilityToolsCategoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-visibility-tools/category/$slug': {
      id: '/ai-visibility-tools/category/$slug'
      path: '/ai-visibility-tools/category/$slug'
      fullPath: '/ai-visibility-tools/category/$slug'
      preLoaderRoute: typeof AiVisibilityToolsCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-visibility-tools/category/open-source': {
      id: '/ai-visibility-tools/category/open-source'
      path: '/ai-visibility-tools/category/open-source'
      fullPath: '/ai-visibility-tools/category/open-source'
      preLoaderRoute: typeof AiVisibilityToolsCategoryOpenSourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-visibility-tools/compare/': {
      id: '/ai-visibility-tools/compare/'
      path: '/ai-visibility-tools/compare'
      fullPath: '/ai-visibility-tools/compare/'
      preLoaderRoute: typeof AiVisibilityToolsCompareIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-visibility-tools/compare/$slug': {
      id: '/ai-visibility-tools/compare/$slug'
      path: '/ai-visibility-tools/compare/$slug'
      fullPath: '/ai-visibility-tools/compare/$slug'
      preLoaderRoute: typeof AiVisibilityToolsCompareSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-visibility-tools/features/': {
      id: '/ai-visibility-tools/features/'
      path: '/ai-visibility-tools/features'
      fullPath: '/ai-visibility-tools/features/'
      preLoaderRoute: typeof AiVisibilityToolsFeaturesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-visibility-tools/features/$slug': {
      id: '/ai-visibility-tools/features/$slug'
      path: '/ai-visibility-tools/features/$slug'
      fullPath: '/ai-visibility-tools/features/$slug'
      preLoaderRoute: typeof AiVisibilityToolsFeaturesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/repo-activity/refresh': {
      id: '/api/repo-activity/refresh'
      path: '/api/repo-activity/refresh'
      fullPath: '/api/repo-activity/refresh'
      preLoaderRoute: typeof ApiRepoActivityRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.mdx/docs/$': {
      id: '/llms.mdx/docs/$'
      path: '/llms.mdx/docs/$'
      fullPath: '/llms.mdx/docs/$'
      preLoaderRoute: typeof LlmsDotmdxDocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og/docs/$': {
      id: '/og/docs/$'
      path: '/og/docs/$'
      fullPath: '/og/docs/$'
      preLoaderRoute: typeof OgDocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/plausible/event/': {
      id: '/api/plausible/event/'
      path: '/api/plausible/event'
      fullPath: '/api/plausible/event/'
      preLoaderRoute: typeof ApiPlausibleEventIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/plausible/js/script/': {
      id: '/api/plausible/js/script/'
      path: '/api/plausible/js/script'
      fullPath: '/api/plausible/js/script/'
      preLoaderRoute: typeof ApiPlausibleJsScriptIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApproachRoute: ApproachRoute,
  BrandRoute: BrandRoute,
  ChangelogRoute: ChangelogRoute,
  CompanyRoute: CompanyRoute,
  DiagnosticRoute: DiagnosticRoute,
  FeaturesRoute: FeaturesRoute,
  GeoRoute: GeoRoute,
  LlmsFullDottxtRoute: LlmsFullDottxtRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  MethodologyRoute: MethodologyRoute,
  OffSiteAeoRoute: OffSiteAeoRoute,
  OgDotpngRoute: OgDotpngRoute,
  PlatformRoute: PlatformRoute,
  PricingRoute: PricingRoute,
  ProductRoute: ProductRoute,
  RepoActivityDotsvgRoute: RepoActivityDotsvgRoute,
  ResearchRoute: ResearchRoute,
  ResultsRoute: ResultsRoute,
  RoadmapRoute: RoadmapRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StatusRoute: StatusRoute,
  VisionRoute: VisionRoute,
  AeoForSlugRoute: AeoForSlugRoute,
  AgentCompanyRoute: AgentCompanyRoute,
  AgentMethodologyRoute: AgentMethodologyRoute,
  AgentPlatformRoute: AgentPlatformRoute,
  AgentResultsRoute: AgentResultsRoute,
  AiSearchSlugRoute: AiSearchSlugRoute,
  AiVisibilityToolsSlugRoute: AiVisibilityToolsSlugRoute,
  ApiOpenapiDotjsonRoute: ApiOpenapiDotjsonRoute,
  ApiSearchRoute: ApiSearchRoute,
  BlogSplatRoute: BlogSplatRoute,
  BlogRssDotxmlRoute: BlogRssDotxmlRoute,
  DocsSplatRoute: DocsSplatRoute,
  GlossarySlugRoute: GlossarySlugRoute,
  OgStatusDotpngRoute: OgStatusDotpngRoute,
  ZhApproachRoute: ZhApproachRoute,
  ZhCompanyRoute: ZhCompanyRoute,
  ZhDiagnosticRoute: ZhDiagnosticRoute,
  ZhGeoRoute: ZhGeoRoute,
  ZhMethodologyRoute: ZhMethodologyRoute,
  ZhPlatformRoute: ZhPlatformRoute,
  ZhProductRoute: ZhProductRoute,
  ZhResearchRoute: ZhResearchRoute,
  ZhResultsRoute: ZhResultsRoute,
  AeoForIndexRoute: AeoForIndexRoute,
  AgentIndexRoute: AgentIndexRoute,
  AiSearchIndexRoute: AiSearchIndexRoute,
  AiVisibilityToolsIndexRoute: AiVisibilityToolsIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  DocsIndexRoute: DocsIndexRoute,
  GlossaryIndexRoute: GlossaryIndexRoute,
  ZhIndexRoute: ZhIndexRoute,
  AiVisibilityToolsAlternativesSlugRoute:
    AiVisibilityToolsAlternativesSlugRoute,
  AiVisibilityToolsCategorySlugRoute: AiVisibilityToolsCategorySlugRoute,
  AiVisibilityToolsCategoryOpenSourceRoute:
    AiVisibilityToolsCategoryOpenSourceRoute,
  AiVisibilityToolsCompareSlugRoute: AiVisibilityToolsCompareSlugRoute,
  AiVisibilityToolsFeaturesSlugRoute: AiVisibilityToolsFeaturesSlugRoute,
  ApiRepoActivityRefreshRoute: ApiRepoActivityRefreshRoute,
  LlmsDotmdxDocsSplatRoute: LlmsDotmdxDocsSplatRoute,
  OgDocsSplatRoute: OgDocsSplatRoute,
  AiVisibilityToolsAlternativesIndexRoute:
    AiVisibilityToolsAlternativesIndexRoute,
  AiVisibilityToolsCategoryIndexRoute: AiVisibilityToolsCategoryIndexRoute,
  AiVisibilityToolsCompareIndexRoute: AiVisibilityToolsCompareIndexRoute,
  AiVisibilityToolsFeaturesIndexRoute: AiVisibilityToolsFeaturesIndexRoute,
  ApiPlausibleEventIndexRoute: ApiPlausibleEventIndexRoute,
  ApiPlausibleJsScriptIndexRoute: ApiPlausibleJsScriptIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
