import type { HumanPageCopy } from "./types";

interface ChinaPageCopy extends HumanPageCopy {
	readonly primaryCta: string;
	readonly closingTitle: string;
	readonly closingBody: string;
}

export const CHINA_SITUATIONS = [
	{
		id: "missing",
		label: "没进候选池",
		question: "采购团队问：这类方案有哪些值得进一步了解？",
		scope: "中国市场 · 中文 · 企业采购问题 · 指定同类品牌",
		answer: "示意答案列出几类选择，没有提到品牌。",
		gap: "品牌没有进入这组问题形成的考虑范围。",
		priority: "先核对品类归属和核心场景是否在公开信息中说清楚。",
	},
	{
		id: "unclear",
		label: "核心卖点被说偏",
		question: "业务负责人问：这个品牌最适合解决什么问题？",
		scope: "中国市场 · 中文 · 核心应用问题 · 品牌事实",
		answer: "示意答案提到品牌，但把次要能力当成了主要卖点。",
		gap: "对外页面里的产品事实和使用场景没有形成一致表达。",
		priority: "先找出被说偏的事实，再确定哪一处公开内容需要核对。",
	},
	{
		id: "displaced",
		label: "竞品占了答案位",
		question: "决策小组问：这几种方案应该怎么比较？",
		scope: "中国市场 · 中文 · 方案比较问题 · 指定对标品牌",
		answer: "示意答案详细解释了对标品牌，品牌只被简短带过。",
		gap: "比较标准、证据细节和品牌优势没有出现在同一段判断里。",
		priority: "先逐项对照答案里的比较标准，再排出最值得补证据的一项。",
	},
	{
		id: "fragmented",
		label: "出海后定位漂移",
		question: "目标市场买家问：这家公司属于哪一类方案？",
		scope: "目标国家 · 目标语言 · 当地购买角色 · 同一品类问题",
		answer: "示例中的当地语言答案把品牌放进了与中国市场不同的品类。",
		gap: "核心品牌事实没有进入当地买家的品类表达和比较语境。",
		priority: "先确认当地品类心智和购买问法，再核对品牌定位差异。",
	},
] as const;

export const CHINA_DIAGNOSTIC_OUTPUTS = [
	{
		id: "scope",
		label: "问题范围",
		body: "明确市场、语言、购买问题和需要对照的品牌。",
	},
	{
		id: "answer",
		label: "答案快照",
		body: "保留当次可见的完整回答、观察时间和引用（如有）。",
	},
	{
		id: "gap",
		label: "竞品差距",
		body: "逐项核对品牌与同类选择被怎样描述和比较。",
	},
	{
		id: "priority",
		label: "优先级清单",
		body: "把值得先核对、先补充、后复盘的工作排出顺序。",
	},
] as const;

export const CHINA_PRODUCT_STAGES = [
	{
		id: "ask",
		label: "圈定问题",
		title: "先把摸底范围钉住",
		body: "从会影响采购选择的问题开始，写清市场、语言、购买角色和对标对象。",
		output: "范围卡",
		scope: "中国市场 · 中文 · 企业采购方 · 这类方案怎么选",
		answer: "本轮只观察三组会影响方案比较的真实问题。",
		gap: "范围未确认时，不把不同市场和不同问法混在一起判断。",
		priority: "会前先确认问题清单和需要对照的品牌。",
	},
	{
		id: "compare",
		label: "拆答案",
		title: "把完整答案逐段拆开",
		body: "保留原回答，再标出品牌、同类选择、比较标准和答案列出的引用。",
		output: "答案拆解",
		scope: "沿用已确认的问题范围和同一次观察记录",
		answer: "答案先定义品类，再列出选择，最后解释适用场景。",
		gap: "品牌出现了，但核心场景没有进入答案的比较段落。",
		priority: "会上先核对答案原文，再讨论品牌表达。",
	},
	{
		id: "improve",
		label: "找掉点",
		title: "找出影响业务判断的缺口",
		body: "把品牌事实与答案逐项对照，说明哪一处缺失、错位或没有证据支撑。",
		output: "掉点记录",
		scope: "只核对已确认问题里可见的品牌事实和比较项",
		answer: "对标品牌有完整适用场景，品牌只有一句概括。",
		gap: "场景证据没有跟核心卖点一起出现。",
		priority: "先补齐最影响采购判断的一项事实说明。",
	},
	{
		id: "follow",
		label: "做复盘",
		title: "用同一范围再核对一次",
		body: "保留相同市场、语言、问题和对标对象，比较后续可见答案发生了什么变化。",
		output: "复盘队列",
		scope: "沿用上次市场、语言、问题和对标对象",
		answer: "示意复查记录里，品牌描述更完整，但比较标准仍未出现。",
		gap: "有变化不等于问题已经解决，仍要回到原答案逐项核对。",
		priority: "下一轮继续复查同一比较项，不扩大观察范围。",
	},
] as const;

export const CHINA_SERVICE_SITUATIONS = [
	{
		id: "visibility",
		number: "01",
		situation: "品牌没进候选池",
		startingPoint: "先查哪些问题没有品牌",
		description: "围绕已经圈定的购买问题，查看品牌是否进入答案列出的考虑范围。",
		scope: "市场、语言、购买问题和同类品牌",
		answer: "示意答案给出同类选择，没有提到品牌。",
		gap: "品牌与这个购买场景的关系没有被答案呈现。",
		priority: "先核对品类归属和核心应用场景。",
		visibleItems: ["客户原问题", "完整答案", "出现的同类品牌"],
	},
	{
		id: "accuracy",
		number: "02",
		situation: "核心卖点被说偏",
		startingPoint: "先对照答案与品牌事实",
		description: "把当次品牌描述与公开事实放在一起，标出缺失、错位或相互冲突的位置。",
		scope: "已确认问题里的品牌描述和公开事实",
		answer: "示意答案把辅助能力写成主要购买理由。",
		gap: "核心能力与应用场景没有形成一致说明。",
		priority: "先核对最影响客户理解的一处事实。",
		visibleItems: ["答案原文", "对应品牌事实", "需要核对的位置"],
	},
	{
		id: "competition",
		number: "03",
		situation: "竞品占了答案位",
		startingPoint: "先拆清答案里的比较标准",
		description: "查看品牌与指定对标对象被怎样介绍，再逐项比较场景、能力和可见引用。",
		scope: "同一购买问题里的品牌、对标对象和比较项",
		answer: "示意答案给对标品牌两项具体理由，只概括品牌名称。",
		gap: "品牌优势没有进入答案采用的比较框架。",
		priority: "先补证据最清楚、最贴近购买问题的一项。",
		visibleItems: ["答案比较项", "品牌与对标对象描述", "可见引用（如有）"],
	},
	{
		id: "expansion",
		number: "04",
		situation: "出海后定位漂移",
		startingPoint: "先建立目标市场对照",
		description: "先定义目标国家、语言和当地购买角色，再查看同一品牌事实如何进入当地品类语境。",
		scope: "目标国家、目标语言、当地购买角色和对标品牌",
		answer: "示例中的当地答案把品牌归入另一类解决方案。",
		gap: "中国市场定位没有按当地买家的品类认知重新表达。",
		priority: "先确认当地品类和问题，再处理语言表达。",
		visibleItems: ["中国市场基线", "当地购买问题", "定位差异"],
	},
] as const;

export const CHINA_MARKETS = [
	{
		id: "china",
		label: "中国市场基线",
		question: "先把中国客户怎么问、品牌怎么被归类记录下来",
		scope: "中国市场 · 中文 · 企业采购方 · 同一品类问题",
		answer: "示意中文答案用本地品类表达介绍品牌和同类选择。",
		gap: "核心卖点与中国买家的比较标准没有完全对齐。",
		priority: "先固定中国市场基线，再定义海外对照范围。",
	},
	{
		id: "target-market",
		label: "目标市场对照",
		question: "只观察已定义市场中当地买家会看到什么",
		scope: "目标国家 · 目标语言 · 当地购买角色 · 指定对标品牌",
		answer: "示例中的当地语言答案采用另一套品类词和比较顺序。",
		gap: "品牌事实没有进入当地买家的购买语境。",
		priority: "先重做当地品类表达，再核对跨市场一致性。",
	},
] as const;

export const CHINA_COPY = {
	home: {
		navLabel: "首页",
		metaTitle: "Yonaris｜AI 品牌摸底，从客户真实问题开始",
		metaDescription: "围绕选定市场、语言和购买问题，核对品牌在 AI 答案中的出现、表达、竞争差距与跨市场定位。",
		eyebrow: "客户的新入口",
		title: "客户开始问 AI，品牌的第一解释权还在你手里吗？",
		lead: "客户把 AI 当作新的搜索入口。Yonaris 提供一张品牌摸底视图：先圈定市场、语言和购买问题，再核对品牌是否进入考虑范围、卖点有没有说准、竞争关系怎样呈现、跨市场定位是否一致。",
		primaryCta: "预约一次 AI 品牌摸底",
		closingTitle: "预约一次 AI 品牌摸底",
		closingBody: "留下姓名、电话和公司。第一次沟通只把市场、语言、购买问题和需要对照的品牌定清楚。",
	},
	product: {
		navLabel: "产品",
		metaTitle: "产品｜品牌为什么没进客户的候选池｜Yonaris",
		metaDescription: "沿着圈定问题、拆答案、找掉点、做复盘四步，形成团队会上可逐条核对的品牌摸底记录。",
		eyebrow: "一份会上能核对的摸底记录",
		title: "品牌为什么没进客户的候选池？",
		lead: "围绕一组会影响采购选择的问题，保留完整答案，逐项核对品牌和对标对象，再排出下一轮动作。最后得到一份能带进会议的品牌摸底记录，而不是一个说不清怎么算的分数。",
		primaryCta: "预约一次品牌摸底",
		closingTitle: "用同一范围做下一次复盘",
		closingBody: "带着市场、语言、购买问题和对标对象开会，先决定哪一处值得核对。",
	},
	approach: {
		navLabel: "服务",
		metaTitle: "服务｜先做品牌体检，再定 GEO 打法｜Yonaris",
		metaDescription: "按未进候选池、卖点说偏、竞品占位和跨市场定位漂移四类问题，先核对答案再确定工作优先级。",
		eyebrow: "先判断问题，再选服务",
		title: "先做品牌体检，再定 GEO 打法。",
		lead: "这里的 GEO，指生成式搜索和 AI 答案中的品牌表现。我们先查清品牌在哪组购买问题里出现偏差，再决定是核对品牌事实、比较说法，还是不同市场的定位。",
		primaryCta: "预约一次品牌体检",
		closingTitle: "先把一个生意问题查清楚",
		closingBody: "从一个市场、一组购买问题和指定对标对象开始，先排出可执行的下一步。",
	},
	geo: {
		navLabel: "全球市场",
		metaTitle: "全球市场｜从中国市场基线到目标市场对照｜Yonaris",
		metaDescription: "先记录中国市场基线，再按目标国家、目标语言、当地购买角色和对标品牌建立出海对照。",
		eyebrow: "中国基线 × 目标市场对照",
		title: "先有中国市场基线，再谈出海本地化",
		lead: "出海不是翻译官网，而是重做一遍当地品类心智。先把中国市场里的品牌定位记录下来，再定义目标国家、目标语言、当地购买角色和对标品牌，只核对这个范围内的可见答案。",
		primaryCta: "圈定目标市场",
		closingTitle: "先选一个市场做对照",
		closingBody: "告诉我们目标国家、语言、当地购买角色和购买问题，先把对照范围定清楚。",
	},
	company: {
		navLabel: "关于我们",
		metaTitle: "关于 Yonaris｜先把 AI 怎么说品牌查清楚",
		metaDescription: "Yonaris 围绕已确认的市场、语言、购买问题和对标品牌，提供可核对的答案记录与工作优先级。",
		eyebrow: "工作边界写在前面",
		title: "不卖玄学排名，先把 AI 怎么说你查清楚",
		lead: "工作范围只包含已确认的市场、语言、购买问题和对标品牌，以及当次可见的答案与引用（如有）。范围之外不推断；输出是可核对记录和优先级建议，不替第三方答案下结论。",
		primaryCta: "圈定一次摸底范围",
		closingTitle: "从可核对的答案开始",
		closingBody: "先确认问题范围，再看答案、差距和优先级；每一步都保留可复盘的依据。",
	},
	diagnostic: {
		navLabel: "预约沟通",
		metaTitle: "预约 AI 品牌摸底｜先定摸底边界｜Yonaris",
		metaDescription: "填写姓名、电话和公司，第一次沟通只确认品牌、市场、语言、购买问题和对标范围。",
		eyebrow: "三项联系方式，先定范围",
		title: "第一次沟通只确认摸底范围",
		lead: "我们只确认品牌、市场、语言、购买问题和需要对照的品牌，判断下一步是否值得继续；这一步不提供诊断结论，也不承诺后续结果。",
		primaryCta: "提交联系方式",
		closingTitle: "先把五项范围说清楚",
		closingBody: "品牌、市场、语言、购买问题、对标对象。无需提前准备复杂材料。",
	},
	privacy: {
		navLabel: "隐私说明",
		metaTitle: "隐私说明｜Yonaris 中国站",
		metaDescription: "说明 Yonaris 中国站咨询表单收集姓名、电话和公司的用途。",
		eyebrow: "咨询信息说明",
		title: "姓名、电话、公司，只用于回复这次咨询",
		lead: "中国站咨询表单只要求这三项可见信息。只有投递服务接受申请后，页面才显示已送出；未确认时会保留已填内容。",
		primaryCta: "返回预约沟通",
		closingTitle: "咨询内容不会显示在公开页面",
		closingBody: "这些信息用于回复本次咨询和安排后续沟通。",
	},
} as const satisfies Record<string, ChinaPageCopy>;
