/* biome-ignore-all lint/suspicious/noTemplateCurlyInString: exact audited values preserve source template syntax */
export const LITERAL_CATEGORIES = [
	"localized-key",
	"raw-evidence",
	"machine-token",
	"proper-noun",
	"developer-only",
	"domain-value",
	"shared-backward-compatible-default",
	"cross-plan-owner",
] as const;

export type LiteralCategory = (typeof LITERAL_CATEGORIES)[number];

export type LiteralClassification = {
	file: string;
	kind: string;
	value: string;
	occurrence: number;
	category: LiteralCategory;
	reason: string;
};

/**
 * Exact, reviewed residuals only. Localized catalog calls and syntax-bound raw
 * evidence interpolations are classified deterministically by the collector.
 * This list deliberately accepts no globs, directory entries, or regexes.
 */
export const PORTAL_LITERAL_CLASSIFICATIONS: LiteralClassification[] = [
	{
		file: "apps/web/src/routes/__root.tsx",
		kind: "metadata-copy",
		value: "width=device-width, initial-scale=1",
		occurrence: 1,
		category: "machine-token",
		reason: "Exact viewport metadata directive is parsed by the browser and is not display copy.",
	},
	{
		file: "apps/web/src/routes/auth/login.tsx",
		kind: "jsx-text",
		value: "demo",
		occurrence: 1,
		category: "machine-token",
		reason: "Literal demo credential shown only in demo mode and submitted byte-identically.",
	},
	{
		file: "apps/web/src/components/word-cloud.tsx",
		kind: "text-prop",
		value: `\`\${it.term} · \${formatNumber(it.count)}\``,
		occurrence: 1,
		category: "raw-evidence",
		reason: "Tooltip combines the raw query term with a locale-formatted count and a neutral separator.",
	},
	{
		file: "apps/web/src/routes/_authed/admin/tools.tsx",
		kind: "jsx-text",
		value: "POST /api/v1/tools/analyze",
		occurrence: 1,
		category: "developer-only",
		reason: "HTTP method and endpoint are developer-facing API reference evidence.",
	},
	{
		file: "apps/web/src/routes/_authed/app/new.tsx",
		kind: "text-prop",
		value: "Acme",
		occurrence: 1,
		category: "proper-noun",
		reason: "Example company proper noun remains unchanged in both UI languages.",
	},
	{
		file: "apps/web/src/components/site-header.tsx",
		kind: "status-capitalization",
		value: "segment.charAt(0).toUpperCase()",
		occurrence: 1,
		category: "machine-token",
		reason:
			"Defensive unknown-segment fallback; the route registration gate requires every reachable segment to have a localized key.",
	},
	{
		file: "apps/web/src/routes/_authed/app/$brand/index.tsx",
		kind: "jsx-text",
		value: "—",
		occurrence: 1,
		category: "machine-token",
		reason: "Exact neutral empty-value dash is intentionally invariant.",
	},
	{
		file: "apps/web/src/routes/_authed/app/$brand/share-of-voice.tsx",
		kind: "jsx-text",
		value: "—",
		occurrence: 1,
		category: "machine-token",
		reason: "Exact neutral empty-value dash is intentionally invariant.",
	},
	{
		file: "apps/web/src/routes/_authed/app/$brand/query-fan-out.tsx",
		kind: "text-prop",
		value:
			'`${t(availability.exposedRuns === 1 ? "fanout.echoOnly.one" : "fanout.echoOnly.many", { count: formatNumber(availability.exposedRuns), })}${ availability.unknownRuns > 0 ? ` ${t(availability.unknownRuns === 1 ? "fanout.echoOnlyUnknown.one" : "fanout.echoOnlyUnknown.many", { count: formatNumber(availability.unknownRuns), })}` : "" }`',
		occurrence: 1,
		category: "localized-key",
		reason: "Every visible template branch is supplied by exact typed bilingual catalog IDs.",
	},
	...(
		[
			["apps/web/src/routes/_authed/app/$brand/settings/brand.tsx", "text-prop", "common.error.unexpected", 1],
			["apps/web/src/routes/_authed/app/$brand/settings/brand.tsx", "text-prop", "formError", 1],
			["apps/web/src/components/brand-onboarding.tsx", "text-prop", "common.error.unexpected", 1],
			["apps/web/src/components/brand-onboarding.tsx", "text-prop", "formError", 1],
			[
				"apps/web/src/components/prompt-wizard.tsx",
				"text-prop",
				"customer.onboardingWizard.validation.identityRequired",
				1,
			],
			["apps/web/src/components/prompt-wizard.tsx", "text-prop", "error", 1],
		] as const
	).map(([file, kind, value, occurrence]) => ({
		file,
		kind,
		value,
		occurrence,
		category: "localized-key" as const,
		reason: "Exact typed MessageId assignment or prop resolves through the bilingual catalog at its display boundary.",
	})),
	...(
		[
			["apps/web/src/components/prompt-wizard.tsx", "text-prop", "idle", 1],
			["apps/web/src/components/prompt-wizard.tsx", "text-prop", "idle", 2],
			["apps/web/src/components/prompt-wizard.tsx", "text-prop", "analyzing", 1],
			["apps/web/src/components/prompt-wizard.tsx", "text-prop", "idle", 3],
			["apps/web/src/components/prompt-wizard.tsx", "text-prop", "review", 1],
		] as const
	).map(([file, kind, value, occurrence]) => ({
		file,
		kind,
		value,
		occurrence,
		category: "machine-token" as const,
		reason: "Exact internal wizard phase token controls state and is never translated as visible copy.",
	})),
	{
		file: "apps/web/src/routes/__root.tsx",
		kind: "metadata-copy",
		value: "title",
		occurrence: 3,
		category: "localized-key",
		reason: "Exact metadata shorthand comes from the bilingual root-head boundary.",
	},
	{
		file: "apps/web/src/routes/__root.tsx",
		kind: "metadata-copy",
		value: "description",
		occurrence: 4,
		category: "localized-key",
		reason: "Exact metadata shorthand comes from the bilingual root-head boundary.",
	},
	{
		file: "apps/web/src/components/progress-bar-chart.tsx",
		kind: "rendered-identifier",
		value: "label",
		occurrence: 2,
		category: "localized-key",
		reason: "Exact rendered label preserves the catalog-backed item label supplied by callers.",
	},
	{
		file: "apps/web/src/components/sampling/browser-runner-device-list.tsx",
		kind: "toast-dialog-copy",
		value: "message",
		occurrence: 1,
		category: "localized-key",
		reason: "Exact confirmation callback forwards the catalog-translated message supplied by the device action.",
	},
	{
		file: "packages/ui/src/components/breadcrumb.tsx",
		kind: "rendered-identifier",
		value: "children",
		occurrence: 1,
		category: "domain-value",
		reason: "Exact shared React child is caller-owned content; the fallback icon contains no display copy.",
	},
	...(
		[
			["rendered-identifier", "report.brandName", 1],
			["rendered-identifier", "extractDomain(report.brandWebsite)", 1],
		] as const
	).map(([kind, value, occurrence]) => ({
		file: "apps/web/src/routes/_authed/reports/index.tsx",
		kind,
		value,
		occurrence,
		category: "raw-evidence" as const,
		reason: "Persisted report brand and derived website-domain values are displayed without translation.",
	})),
	...(
		[
			["jsx-text", "(", 1],
			["jsx-text", ")", 1],
			["rendered-identifier", "report.status", 1],
		] as const
	).map(([kind, value, occurrence]) => ({
		file: "apps/web/src/routes/_authed/reports/index.tsx",
		kind,
		value,
		occurrence,
		category: "domain-value" as const,
		reason: "Exact report-domain punctuation or unknown persisted status fallback is not Portal product copy.",
	})),

	...(
		[
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "metadata-copy", "AI Share of Voice Report", 1],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "metadata-copy", "noindex, nofollow", 1],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "jsx-text", "Report status:", 1],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "rendered-identifier", "report.status", 1],
			[
				"apps/web/src/routes/_authed/reports/render/$reportId.tsx",
				"rendered-identifier",
				'new Date(report.createdAt).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })',
				1,
			],
			[
				"apps/web/src/routes/_authed/reports/render/$reportId.tsx",
				"display-locale",
				'new Date(report.createdAt).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })',
				1,
			],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "jsx-text", "AI Share of Voice Report", 1],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "rendered-identifier", "report.brandName", 1],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "template-prose", "`${overallSoV}%`", 1],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "jsx-text", "N/A", 1],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "jsx-text", "Share of Voice", 1],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "rendered-identifier", "sovLevel.label", 1],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "jsx-text", "&mdash;", 1],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "rendered-identifier", "sovLevel.description", 1],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "text-prop", "Prompts Tested", 1],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "text-prop", "Brand Mentions", 1],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "text-prop", "Competitors", 1],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "text-prop", "AI Engine Performance", 1],
			[
				"apps/web/src/routes/_authed/reports/render/$reportId.tsx",
				"text-prop",
				"`Brand mention rate across ${engineBreakdown.reduce((s, e) => s + e.totalRuns, 0)} evaluations`",
				1,
			],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "rendered-identifier", "eng.engine", 1],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "rendered-identifier", "eng.mentionRate", 1],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "jsx-text", "%", 1],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "rendered-identifier", "eng.brandMentions", 1],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "jsx-text", "of", 1],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "rendered-identifier", "eng.totalRuns", 1],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "jsx-text", "runs", 1],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "text-prop", "Competitive Landscape", 1],
			[
				"apps/web/src/routes/_authed/reports/render/$reportId.tsx",
				"text-prop",
				"Share of voice comparison across all tested prompts",
				1,
			],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "jsx-text", "Brand", 1],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "jsx-text", "SoV", 1],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "jsx-text", "Share", 1],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "rendered-identifier", "row.name", 1],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "rendered-identifier", "row.sov", 1],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "jsx-text", "%", 2],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "text-prop", "Mention Rate", 1],
			[
				"apps/web/src/routes/_authed/reports/render/$reportId.tsx",
				"text-prop",
				"Each prompt is evaluated multiple times across AI engines — mentions show total appearances, unique prompts show how many distinct prompts include the brand",
				1,
			],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "jsx-text", "Brand", 2],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "jsx-text", "Mentions", 1],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "jsx-text", "Unique Prompts", 1],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "rendered-identifier", "c.name", 1],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "rendered-identifier", "c.mentionCount", 1],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "jsx-text", "/", 1],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "rendered-identifier", "simpleRuns.length", 1],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "rendered-identifier", "c.promptCount", 1],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "jsx-text", "/", 2],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "rendered-identifier", "totalPrompts", 1],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "text-prop", "Prompt Analysis", 1],
			[
				"apps/web/src/routes/_authed/reports/render/$reportId.tsx",
				"text-prop",
				"Share of voice for representative prompts — strengths and growth opportunities",
				1,
			],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "jsx-text", "Prompt Analysis (continued)", 1],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "text-prop", "Content Gaps", 1],
			[
				"apps/web/src/routes/_authed/reports/render/$reportId.tsx",
				"text-prop",
				"`Prompts where competitors appear but ${report.brandName} does not — highest-value opportunities`",
				1,
			],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "jsx-text", "Prompt", 1],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "jsx-text", "Competitors Found", 1],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "rendered-identifier", "gap.promptValue", 1],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "rendered-identifier", "c", 1],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "jsx-text", "+", 1],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "rendered-identifier", "report.brandName", 2],
			[
				"apps/web/src/routes/_authed/reports/render/$reportId.tsx",
				"jsx-text",
				"appears in all prompts where competitors are mentioned.",
				1,
			],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "text-prop", "Top AI Search Queries", 1],
			[
				"apps/web/src/routes/_authed/reports/render/$reportId.tsx",
				"text-prop",
				"Common web search queries AI models run when answering prompts in your category",
				1,
			],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "jsx-text", "Query", 1],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "jsx-text", "Competitors Found", 2],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "jsx-text", "Brand Mentioned", 1],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "rendered-identifier", "q.query", 1],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "rendered-identifier", "q.competitorCount", 1],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "jsx-text", "&#10003;", 1],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "jsx-text", "&mdash;", 2],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "text-prop", "Share of Voice Opportunity", 1],
			[
				"apps/web/src/routes/_authed/reports/render/$reportId.tsx",
				"text-prop",
				"Overview of your current AI share of voice and growth potential",
				1,
			],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "jsx-text", "Prompts With Mentions", 1],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "jsx-text", "Total Prompts Tested", 1],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "jsx-text", "Overall SoV", 1],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "jsx-text", "Opportunity", 1],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "jsx-text", "Recommendation", 1],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "rendered-identifier", "promptsWithMentions", 1],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "rendered-identifier", "totalPrompts", 2],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "rendered-identifier", "overallSoV", 1],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "jsx-text", "0", 1],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "jsx-text", "%", 3],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "jsx-text", "High", 1],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "jsx-text", "Medium", 1],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "jsx-text", "Low", 1],
			[
				"apps/web/src/routes/_authed/reports/render/$reportId.tsx",
				"jsx-text",
				"Prioritize content creation to establish AI presence",
				1,
			],
			[
				"apps/web/src/routes/_authed/reports/render/$reportId.tsx",
				"jsx-text",
				"Expand content to increase brand share of voice",
				1,
			],
			[
				"apps/web/src/routes/_authed/reports/render/$reportId.tsx",
				"jsx-text",
				"Maintain leadership and defend competitive position",
				1,
			],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "text-prop", "What Should I Do Next?", 1],
			[
				"apps/web/src/routes/_authed/reports/render/$reportId.tsx",
				"text-prop",
				"`Prompts where competitors outperform ${report.brandName} — your biggest growth opportunities`",
				1,
			],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "rendered-identifier", "report.brandName", 3],
			[
				"apps/web/src/routes/_authed/reports/render/$reportId.tsx",
				"jsx-text",
				"leads or matches competitors across all tested prompts.",
				1,
			],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "jsx-text", "Prompt", 2],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "jsx-text", "Current SoV", 1],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "jsx-text", "Top Competitor SoV", 1],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "jsx-text", "Goal SoV", 1],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "jsx-text", "Recommendation", 2],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "rendered-identifier", "o.promptValue", 1],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "rendered-identifier", "o.brandSoV", 1],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "jsx-text", "%", 4],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "rendered-identifier", "o.maxCompSoV", 1],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "jsx-text", "%", 5],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "rendered-identifier", "o.goalSoV", 1],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "jsx-text", "%", 6],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "jsx-text", "Write", 1],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "rendered-identifier", "o.articleCount", 1],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "jsx-text", "LLM-friendly articles on &ldquo;", 1],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "rendered-identifier", "o.promptValue", 2],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "jsx-text", "&rdquo;", 1],
			[
				"apps/web/src/routes/_authed/reports/render/$reportId.tsx",
				"jsx-text",
				"Ready to Optimize Your AI answer presence?",
				1,
			],
			[
				"apps/web/src/routes/_authed/reports/render/$reportId.tsx",
				"jsx-text",
				"Take your brand's AI presence to the next level with",
				1,
			],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "rendered-identifier", "appName", 1],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "jsx-text", "Strategic Optimization", 1],
			[
				"apps/web/src/routes/_authed/reports/render/$reportId.tsx",
				"jsx-text",
				"Develop content strategies that increase your brand's share of voice in AI responses",
				1,
			],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "jsx-text", "Continuous Monitoring", 1],
			[
				"apps/web/src/routes/_authed/reports/render/$reportId.tsx",
				"jsx-text",
				"Track your AI share of voice across hundreds of relevant prompts and topics",
				1,
			],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "jsx-text", "Competitive Advantage", 1],
			[
				"apps/web/src/routes/_authed/reports/render/$reportId.tsx",
				"jsx-text",
				"Stay ahead of competitors in the rapidly evolving AI search landscape",
				1,
			],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "jsx-text", "Get started with", 1],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "rendered-identifier", "appName", 2],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "jsx-text", "today", 1],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "jsx-text", "Visit", 1],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "rendered-identifier", "appUrl", 1],
			[
				"apps/web/src/routes/_authed/reports/render/$reportId.tsx",
				"jsx-text",
				"to learn more about our AI answer presence platform and services.",
				1,
			],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "jsx-text", "AI Share of Voice Report", 2],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "rendered-identifier", "brand", 1],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "rendered-identifier", "title", 1],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "rendered-identifier", "subtitle", 1],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "rendered-identifier", "children", 1],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "rendered-identifier", "value", 1],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "rendered-identifier", "label", 1],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "jsx-text", "Strength", 1],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "jsx-text", "Opportunity", 2],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "rendered-identifier", "label", 2],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "rendered-identifier", "value", 2],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "rendered-identifier", "children", 2],
			["apps/web/src/routes/_authed/reports/render/$reportId.tsx", "rendered-identifier", "brandUrl", 1],
		] as const
	).map(([file, kind, value, occurrence]) => ({
		file,
		kind,
		value,
		occurrence,
		category: "cross-plan-owner" as const,
		reason:
			"Exact printable report residual belongs to portal-output-languages Task 4 and remains deferred until explicit outputLanguage propagation.",
	})),
	...(
		[
			[
				"apps/web/src/routes/_authed/admin/access.tsx",
				"raw-error-interpolation",
				"rawErrorDetail(createWorkspace.error)",
				1,
			],
			[
				"apps/web/src/routes/_authed/admin/access.tsx",
				"raw-error-interpolation",
				"rawErrorDetail(createAccount.error)",
				1,
			],
			[
				"apps/web/src/routes/_authed/admin/access.tsx",
				"raw-error-interpolation",
				"rawErrorDetail(workspaces.error)",
				1,
			],
			["apps/web/src/routes/_authed/admin/access.tsx", "raw-error-interpolation", "rawErrorDetail(access.error)", 1],
			[
				"apps/web/src/routes/_authed/admin/access.tsx",
				"raw-error-interpolation",
				"rawErrorDetail(resetPassword.error)",
				1,
			],
			["apps/web/src/routes/_authed/reports/index.tsx", "raw-error-interpolation", "error.message", 1],
			["apps/web/src/routes/_authed/reports/index.tsx", "raw-error-interpolation", "String(error)", 1],
			["apps/web/src/routes/_authed/admin/index.tsx", "raw-error-interpolation", "error.detail", 1],
			["apps/web/src/routes/_authed/admin/index.tsx", "raw-error-interpolation", "error", 1],
			["apps/web/src/routes/_authed/admin/sampling/$taskId.tsx", "raw-error-interpolation", "detail", 1],
			["apps/web/src/routes/_authed/admin/sampling/$taskId.tsx", "raw-error-interpolation", "detail", 2],
			[
				"apps/web/src/routes/_authed/admin/sampling/devices.tsx",
				"raw-error-interpolation",
				"rawErrorDetail(contextQuery.error ?? devicesQuery.error)",
				1,
			],
			["apps/web/src/routes/_authed/admin/sampling/index.tsx", "raw-error-interpolation", "actionError.detail", 1],
			[
				"apps/web/src/routes/_authed/admin/sampling/index.tsx",
				"raw-error-interpolation",
				"rawErrorDetail(devicesQuery.error ?? overseasQuery.error)",
				1,
			],
			[
				"apps/web/src/routes/_authed/admin/sampling/index.tsx",
				"raw-error-interpolation",
				"rawErrorDetail(contextQuery.error ?? listQuery.error)",
				1,
			],
			["apps/web/src/routes/_authed/admin/tools.tsx", "raw-error-interpolation", "error.detail", 1],
			[
				"apps/web/src/routes/_authed/admin/tools.tsx",
				"raw-error-interpolation",
				"rawErrorDetail(opportunityScopes.error)",
				1,
			],
			["apps/web/src/routes/_authed/admin/workflows.tsx", "raw-error-interpolation", "error", 1],
			["apps/web/src/routes/_authed/admin/workflows.tsx", "raw-error-interpolation", "job.failedReason", 1],
			["apps/web/src/routes/_authed/admin/workflows.tsx", "raw-error-interpolation", "logsError", 1],
			["apps/web/src/routes/_authed/admin/workflows.tsx", "raw-error-interpolation", 'logs.join("\\n")', 1],
			["apps/web/src/routes/_authed/admin/workflows.tsx", "raw-error-interpolation", "retryError", 1],
			["apps/web/src/routes/_authed/admin/workflows.tsx", "raw-error-interpolation", "error", 2],
			["apps/web/src/routes/_authed/reports/index.tsx", "raw-error-interpolation", "submitError.message", 1],
			["apps/web/src/components/opportunities-generation-control.tsx", "raw-error-interpolation", "message.detail", 1],
			["apps/web/src/components/localized-raw-detail.tsx", "raw-error-interpolation", "detail", 1],
			["apps/web/src/components/sampling/browser-runner-device-list.tsx", "raw-error-interpolation", "error.detail", 1],
			[
				"apps/web/src/components/sampling/browser-runner-extension-install.tsx",
				"raw-error-interpolation",
				"metadataError.detail",
				1,
			],
			["apps/web/src/components/sampling/overseas-run-now-dialog.tsx", "raw-error-interpolation", "error.detail", 1],
			[
				"apps/web/src/components/sampling/sampling-batch-create-dialog.tsx",
				"raw-error-interpolation",
				"error.detail",
				1,
			],
			["apps/web/src/components/sampling/sampling-run-now-dialog.tsx", "raw-error-interpolation", "error.detail", 1],
			[
				"apps/web/src/components/sampling/sampling-task-workbench.tsx",
				"raw-error-interpolation",
				"task.automation.needsHumanReason",
				1,
			],
			[
				"apps/web/src/components/sampling/sampling-task-workbench.tsx",
				"raw-error-interpolation",
				"evidenceArtifactsError",
				1,
			],
			["apps/web/src/components/sampling/sampling-task-workbench.tsx", "raw-error-interpolation", "item.error", 1],
			["apps/web/src/components/sampling/sampling-task-workbench.tsx", "raw-error-interpolation", "item.error", 2],
			[
				"apps/web/src/components/sampling/sampling-task-workbench.tsx",
				"raw-error-interpolation",
				"presentation.detail",
				1,
			],
			["apps/web/src/components/sampling/sampling-task-workbench.tsx", "raw-error-interpolation", "error.detail", 1],
			["apps/web/src/components/sampling/sampling-task-workbench.tsx", "raw-error-interpolation", "heartbeatError", 1],
		] as const
	).map(([file, kind, value, occurrence]) => ({
		file,
		kind,
		value,
		occurrence,
		category: "raw-evidence" as const,
		reason:
			"Exact raw or developer-detail value is rendered byte-identically only inside a labelled raw-detail region.",
	})),
	...(
		[
			["packages/ui/src/components/sidebar.tsx", "backward-compatible-default", "Sidebar", 1],
			["packages/ui/src/components/sidebar.tsx", "backward-compatible-default", "Displays the mobile sidebar.", 1],
			["packages/ui/src/components/sidebar.tsx", "backward-compatible-default", "Toggle Sidebar", 1],
			["packages/ui/src/components/sidebar.tsx", "backward-compatible-default", "Toggle Sidebar", 2],
			["packages/ui/src/components/breadcrumb.tsx", "backward-compatible-default", "breadcrumb", 1],
			["packages/ui/src/components/breadcrumb.tsx", "backward-compatible-default", "More", 1],
			["packages/ui/src/components/tags-input.tsx", "backward-compatible-default", "Select...", 1],
			["packages/ui/src/components/tags-input.tsx", "backward-compatible-default", "Search...", 1],
			["packages/ui/src/components/tags-input.tsx", "backward-compatible-default", "No results.", 1],
			["packages/ui/src/components/tags-input.tsx", "backward-compatible-default", "Maximum reached", 1],
			["packages/ui/src/components/tags-input.tsx", "backward-compatible-default", "Type or paste to add a value", 1],
			["packages/ui/src/components/tags-input.tsx", "backward-compatible-default", "Add", 1],
			["packages/ui/src/components/tags-input.tsx", "backward-compatible-default", "`Remove ${tag}`", 1],
		] as const
	).map(([file, kind, value, occurrence]) => ({
		file,
		kind,
		value,
		occurrence,
		category: "shared-backward-compatible-default" as const,
		reason: "Exact shared-package fallback remains for external callers; Portal call sites supply localized values.",
	})),
	...(
		[
			["apps/web/src/components/sampling/browser-runner-device-list.tsx", "jsx-text", "Windows", 1],
			["apps/web/src/components/sampling/browser-runner-device-list.tsx", "jsx-text", "macOS", 1],
			["apps/web/src/components/sampling/overseas-run-now-dialog.tsx", "metadata-copy", "ChatGPT", 1],
			["apps/web/src/components/sampling/overseas-run-now-dialog.tsx", "metadata-copy", "Perplexity", 1],
			["apps/web/src/components/sampling/overseas-run-now-dialog.tsx", "metadata-copy", "Gemini", 1],
			["apps/web/src/components/sampling/overseas-run-now-dialog.tsx", "metadata-copy", "Copilot", 1],
			["apps/web/src/components/sampling/overseas-run-now-dialog.tsx", "metadata-copy", "Google AI Mode", 1],
			["apps/web/src/components/sampling/overseas-run-now-dialog.tsx", "metadata-copy", "Google AI Overview", 1],
		] as const
	).map(([file, kind, value, occurrence]) => ({
		file,
		kind,
		value,
		occurrence,
		category: "proper-noun" as const,
		reason: "Exact provider, product, or operating-system proper noun is intentionally invariant.",
	})),
	...(
		[
			["apps/web/src/routes/auth/login.tsx", "jsx-text", "demo@example.com", 1],
			["apps/web/src/routes/_authed/admin/access.tsx", "text-prop", "https://example.com", 1],
			["apps/web/src/routes/_authed/admin/index.tsx", "text-prop", "0", 1],
			["apps/web/src/routes/_authed/admin/index.tsx", "text-prop", "0", 2],
			["apps/web/src/routes/_authed/admin/index.tsx", "text-prop", "0", 3],
			["apps/web/src/routes/_authed/admin/index.tsx", "jsx-text", "(", 1],
			["apps/web/src/routes/_authed/admin/index.tsx", "jsx-text", ")", 1],
			["apps/web/src/routes/_authed/admin/index.tsx", "jsx-text", "0", 1],
			["apps/web/src/routes/_authed/admin/index.tsx", "jsx-text", "+", 1],
			["apps/web/src/routes/_authed/admin/index.tsx", "jsx-text", "-", 1],
			["apps/web/src/routes/_authed/admin/sampling/index.tsx", "jsx-text", "·", 1],
			["apps/web/src/routes/_authed/admin/sampling/index.tsx", "jsx-text", "/", 1],
			["apps/web/src/routes/_authed/admin/tools.tsx", "text-prop", "https://example.com", 1],
			["apps/web/src/routes/_authed/admin/tools.tsx", "jsx-text", "(", 1],
			["apps/web/src/routes/_authed/admin/tools.tsx", "jsx-text", "—", 1],
			["apps/web/src/routes/_authed/admin/tools.tsx", "jsx-text", ")", 1],
			["apps/web/src/routes/_authed/admin/tools.tsx", "jsx-text", ".", 1],
			["apps/web/src/routes/_authed/admin/workflows.tsx", "jsx-text", "&mdash;", 1],
			["apps/web/src/routes/_authed/admin/workflows.tsx", "jsx-text", "-", 1],
			["apps/web/src/routes/_authed/admin/workflows.tsx", "jsx-text", ")", 1],
			["apps/web/src/routes/_authed/admin/workflows.tsx", "jsx-text", "/", 1],
			["apps/web/src/routes/_authed/admin/workflows.tsx", "jsx-text", "%", 1],
			["apps/web/src/routes/_authed/admin/workflows.tsx", "jsx-text", "%", 2],
			["apps/web/src/routes/_authed/app/$brand/index.tsx", "jsx-text", "%", 1],
			["apps/web/src/routes/_authed/app/$brand/prompts/$promptId.tsx", "jsx-text", "|", 1],
			["apps/web/src/routes/_authed/app/$brand/prompts/$promptId.tsx", "jsx-text", ":", 1],
			["apps/web/src/routes/_authed/app/$brand/prompts/$promptId.tsx", "jsx-text", "|", 2],
			["apps/web/src/routes/_authed/app/$brand/prompts/$promptId.tsx", "jsx-text", ":", 2],
			["apps/web/src/routes/_authed/app/$brand/prompts/$promptId.tsx", "jsx-text", "|", 3],
			["apps/web/src/routes/_authed/app/$brand/query-fan-out.tsx", "jsx-text", "×", 1],
			["apps/web/src/routes/_authed/app/$brand/share-of-voice.tsx", "jsx-text", "%", 1],
			["apps/web/src/routes/_authed/app/$brand/share-of-voice.tsx", "jsx-text", "#", 1],
			["apps/web/src/routes/_authed/app/$brand/share-of-voice.tsx", "jsx-text", "%", 2],
			["apps/web/src/routes/_authed/app/$brand/visibility.tsx", "jsx-text", ".", 1],
			["apps/web/src/routes/_authed/app/index.tsx", "jsx-text", "+", 1],
			["apps/web/src/routes/__root.tsx", "metadata-copy", "1200", 1],
			["apps/web/src/routes/__root.tsx", "metadata-copy", "630", 1],
			["apps/web/src/routes/__root.tsx", "metadata-copy", "website", 1],
			["apps/web/src/routes/__root.tsx", "metadata-copy", "summary_large_image", 1],
			["apps/web/src/components/base-chart-print.tsx", "jsx-text", "%", 1],
			["apps/web/src/components/base-chart.tsx", "jsx-text", "%", 1],
			["apps/web/src/components/base-chart.tsx", "jsx-text", "%", 2],
			["apps/web/src/components/base-chart.tsx", "jsx-text", "%", 3],
			["apps/web/src/components/chart-export-preview.tsx", "jsx-text", "%", 1],
			["apps/web/src/components/citations/google-shopping-card.tsx", "jsx-text", "(", 1],
			["apps/web/src/components/citations/google-shopping-card.tsx", "jsx-text", ")", 1],
			["apps/web/src/components/citations/google-shopping-card.tsx", "jsx-text", "(", 2],
			["apps/web/src/components/citations/google-shopping-card.tsx", "jsx-text", ")", 2],
			["apps/web/src/components/citations/recent-changes-card.tsx", "jsx-text", "→", 1],
			["apps/web/src/components/citations/top-urls-card.tsx", "jsx-text", "&mdash;", 1],
			["apps/web/src/components/citations/trend-area-chart.tsx", "jsx-text", "%", 1],
			["apps/web/src/components/customer-programs-view.tsx", "jsx-text", "/", 1],
			["apps/web/src/components/fanout-sections.tsx", "jsx-text", "×", 1],
			["apps/web/src/components/measurement-scope-provision-dialog.tsx", "text-prop", "cn-zh", 1],
			["apps/web/src/components/measurement-scope-provision-dialog.tsx", "text-prop", "CN", 1],
			["apps/web/src/components/measurement-scope-provision-dialog.tsx", "text-prop", "zh-CN", 1],
			["apps/web/src/components/measurement-scope-provision-dialog.tsx", "text-prop", "Asia/Shanghai", 1],
			["apps/web/src/components/measurement-scope-switcher.tsx", "jsx-text", "/", 1],
			["apps/web/src/components/measurement-scope-switcher.tsx", "jsx-text", "/", 2],
			["apps/web/src/components/measurement-scope-switcher.tsx", "jsx-text", "/", 3],
			["apps/web/src/components/nav-app-info.tsx", "jsx-text", "v", 1],
			["apps/web/src/components/opportunities-generation-control.tsx", "jsx-text", "·", 1],
			["apps/web/src/components/opportunities-generation-control.tsx", "jsx-text", "·", 2],
			["apps/web/src/components/opportunities-generation-control.tsx", "jsx-text", "·", 3],
			["apps/web/src/components/opportunities-report.tsx", "jsx-text", "·", 1],
			["apps/web/src/components/opportunities-report.tsx", "jsx-text", "(", 1],
			["apps/web/src/components/opportunities-report.tsx", "jsx-text", ")", 1],
			["apps/web/src/components/opportunities-report.tsx", "jsx-text", "▾", 1],
			["apps/web/src/components/opportunities-report.tsx", "jsx-text", "(", 2],
			["apps/web/src/components/opportunities-report.tsx", "jsx-text", ")", 2],
			["apps/web/src/components/prompt-chart-print.tsx", "jsx-text", "%", 1],
			["apps/web/src/components/prompts-list-editor.tsx", "text-prop", "—", 1],
			["apps/web/src/components/response-snapshot-panel.tsx", "jsx-text", "·", 1],
			["apps/web/src/components/response-snapshot-panel.tsx", "jsx-text", "(", 1],
			["apps/web/src/components/response-snapshot-panel.tsx", "jsx-text", ")", 1],
			["apps/web/src/components/response-snapshot-panel.tsx", "jsx-text", ":", 1],
			["apps/web/src/components/response-snapshot-panel.tsx", "jsx-text", ":", 2],
			["apps/web/src/components/response-snapshot-panel.tsx", "jsx-text", ":", 3],
			["apps/web/src/components/sampling/browser-runner-device-list.tsx", "jsx-text", "·", 1],
			["apps/web/src/components/sampling/browser-runner-extension-install.tsx", "jsx-text", "SHA-256", 1],
			["apps/web/src/components/sampling/browser-runner-extension-install.tsx", "jsx-text", "chrome://extensions", 1],
			["apps/web/src/components/sampling/sampling-batch-card.tsx", "jsx-text", "%", 1],
			["apps/web/src/components/sampling/sampling-batch-create-dialog.tsx", "jsx-text", "·", 1],
			["apps/web/src/components/sampling/sampling-batch-create-dialog.tsx", "jsx-text", "/", 1],
			["apps/web/src/components/sampling/sampling-batch-create-dialog.tsx", "jsx-text", "·", 2],
			["apps/web/src/components/sampling/sampling-batch-list.tsx", "jsx-text", "/", 1],
			["apps/web/src/components/sampling/sampling-batch-list.tsx", "jsx-text", "·", 1],
			["apps/web/src/components/sampling/sampling-batch-list.tsx", "jsx-text", "/", 2],
			["apps/web/src/components/sampling/sampling-batch-list.tsx", "jsx-text", "/", 3],
			["apps/web/src/components/sampling/sampling-batch-list.tsx", "jsx-text", "%", 1],
			["apps/web/src/components/sampling/sampling-task-workbench.tsx", "jsx-text", "–", 1],
			["apps/web/src/components/sampling/sampling-task-workbench.tsx", "text-prop", "https://...", 1],
			["apps/web/src/components/sampling/sampling-task-workbench.tsx", "jsx-text", "·", 1],
			["apps/web/src/components/sampling/sampling-task-workbench.tsx", "jsx-text", "%", 1],
			["apps/web/src/components/sampling/sampling-task-workbench.tsx", "jsx-text", "SHA-256", 1],
			["apps/web/src/components/sampling/sampling-task-workbench.tsx", "jsx-text", ":", 1],
			["apps/web/src/components/sampling/sampling-task-workbench.tsx", "jsx-text", "/", 1],
			["apps/web/src/components/share-of-voice-donut.tsx", "jsx-text", ":", 1],
			["apps/web/src/components/share-of-voice-donut.tsx", "jsx-text", "%", 1],
			["apps/web/src/components/trend-chart.tsx", "jsx-text", "%", 1],
			["apps/web/src/components/visibility-bar.tsx", "jsx-text", "%", 1],
			["packages/ui/src/components/tags-input.tsx", "rendered-identifier", "v", 1],
			["packages/ui/src/components/tags-input.tsx", "jsx-text", "&ldquo;", 1],
			["packages/ui/src/components/tags-input.tsx", "jsx-text", "&rdquo;", 1],
		] as const
	).map(([file, kind, value, occurrence]) => ({
		file,
		kind,
		value,
		occurrence,
		category: "machine-token" as const,
		reason: "Exact machine-readable token, neutral symbol, URL, locale, or code is intentionally invariant.",
	})),
	...(
		[
			["apps/web/src/routes/auth/login.tsx", "rendered-identifier", "error", 1],
			["apps/web/src/routes/auth/login.tsx", "rendered-identifier", "error", 2],
			["apps/web/src/routes/auth/register.tsx", "rendered-identifier", "error", 1],
			["apps/web/src/routes/auth/reset-password.tsx", "rendered-identifier", "error", 1],
			["apps/web/src/routes/_authed/admin/index.tsx", "text-prop", "props.label", 1],
			["apps/web/src/routes/_authed/admin/sampling/$taskId.tsx", "rendered-identifier", "title", 1],
			["apps/web/src/routes/_authed/admin/sampling/$taskId.tsx", "rendered-identifier", "description", 1],
			["apps/web/src/routes/_authed/admin/sampling/index.tsx", "rendered-identifier", "title", 1],
			["apps/web/src/routes/_authed/admin/tools.tsx", "rendered-identifier", "label", 1],
			["apps/web/src/routes/_authed/admin/tools.tsx", "rendered-identifier", "title", 1],
			["apps/web/src/routes/_authed/admin/workflows.tsx", "rendered-identifier", "title", 1],
			["apps/web/src/routes/_authed/app/$brand/citations.tsx", "rendered-identifier", "emptyDescription", 1],
			["apps/web/src/routes/_authed/app/$brand/index.tsx", "rendered-identifier", "label", 1],
			["apps/web/src/routes/_authed/app/$brand/index.tsx", "rendered-identifier", "title", 1],
			["apps/web/src/routes/_authed/app/$brand/index.tsx", "rendered-identifier", "label", 2],
			["apps/web/src/routes/_authed/app/$brand/query-fan-out.tsx", "rendered-identifier", "label", 1],
			["apps/web/src/routes/_authed/app/$brand/query-fan-out.tsx", "text-prop", "tipLabel", 1],
			["apps/web/src/routes/_authed/app/$brand/query-fan-out.tsx", "rendered-identifier", "label", 2],
			[
				"apps/web/src/routes/_authed/app/$brand/settings/members.tsx",
				"rendered-identifier",
				"roleLabel(inviteRole)",
				1,
			],
			[
				"apps/web/src/routes/_authed/app/$brand/settings/members.tsx",
				"rendered-identifier",
				"roleLabel(member.role)",
				1,
			],
			[
				"apps/web/src/routes/_authed/app/$brand/settings/members.tsx",
				"rendered-identifier",
				"roleLabel(invitation.role)",
				1,
			],
			["apps/web/src/routes/__root.tsx", "metadata-copy", "description", 1],
			["apps/web/src/routes/__root.tsx", "metadata-copy", "title", 1],
			["apps/web/src/routes/__root.tsx", "metadata-copy", "description", 2],
			["apps/web/src/routes/__root.tsx", "metadata-copy", "title", 2],
			["apps/web/src/routes/__root.tsx", "metadata-copy", "description", 3],
			["apps/web/src/components/base-chart-print.tsx", "rendered-identifier", "title", 1],
			["apps/web/src/components/base-chart-print.tsx", "rendered-identifier", "title", 2],
			["apps/web/src/components/base-chart.tsx", "rendered-identifier", "title", 1],
			["apps/web/src/components/base-chart.tsx", "rendered-identifier", "chartConfig[name as string]?.label", 1],
			[
				"apps/web/src/components/base-chart.tsx",
				"rendered-identifier",
				"chartConfig[item.dataKey as string]?.label",
				1,
			],
			["apps/web/src/components/citations/google-shopping-card.tsx", "rendered-identifier", "label", 1],
			["apps/web/src/components/citations/recent-changes-card.tsx", "rendered-identifier", "change.previousTitle", 1],
			["apps/web/src/components/citations/recent-changes-card.tsx", "rendered-identifier", "change.currentTitle", 1],
			["apps/web/src/components/citations/recent-changes-card.tsx", "rendered-identifier", "description", 1],
			["apps/web/src/components/citations/reddit-card.tsx", "metadata-copy", "u.title", 1],
			["apps/web/src/components/citations/reddit-card.tsx", "metadata-copy", "u.title", 2],
			["apps/web/src/components/citations/reddit-card.tsx", "rendered-identifier", "u.title", 1],
			["apps/web/src/components/citations/shared.tsx", "rendered-identifier", "label", 1],
			["apps/web/src/components/citations/stats-cards.tsx", "rendered-identifier", "title", 1],
			["apps/web/src/components/citations/top-urls-card.tsx", "rendered-identifier", "t.label", 1],
			[
				"apps/web/src/components/citations/top-urls-card.tsx",
				"rendered-identifier",
				"getCategoryLabel(citation.category, t)",
				1,
			],
			["apps/web/src/components/citations/track-domain-popover.tsx", "rendered-identifier", "error", 1],
			["apps/web/src/components/citations/trend-area-chart.tsx", "metadata-copy", "meta[k]?.label", 1],
			["apps/web/src/components/citations/trend-area-chart.tsx", "rendered-identifier", "title", 1],
			["apps/web/src/components/citations/trend-area-chart.tsx", "rendered-identifier", "meta[r.k]?.label", 1],
			["apps/web/src/components/col-head.tsx", "rendered-identifier", "label", 1],
			["apps/web/src/components/fanout-sections.tsx", "text-prop", "label", 1],
			["apps/web/src/components/fanout-sections.tsx", "text-prop", "help", 1],
			["apps/web/src/components/fanout-sections.tsx", "rendered-identifier", "help", 1],
			["apps/web/src/components/filter-bar.tsx", "rendered-identifier", "label", 1],
			["apps/web/src/components/filter-bar.tsx", "text-prop", "labelForModel(selected, allModelsLabel)", 1],
			["apps/web/src/components/filter-bar.tsx", "rendered-identifier", "labelForModel(model, allModelsLabel)", 1],
			["apps/web/src/components/filter-bar.tsx", "text-prop", "getLookbackLabel(selected, t)", 1],
			["apps/web/src/components/filter-bar.tsx", "text-prop", "placeholder", 1],
			["apps/web/src/components/filter-bar.tsx", "rendered-identifier", "label", 2],
			["apps/web/src/components/filtered-list-shell.tsx", "rendered-identifier", "noMatchesTitle", 1],
			["apps/web/src/components/filtered-list-shell.tsx", "rendered-identifier", "noMatchesDescription", 1],
			["apps/web/src/components/full-page-card.tsx", "rendered-identifier", "title", 1],
			["apps/web/src/components/full-page-card.tsx", "rendered-identifier", "subtitle", 1],
			["apps/web/src/components/language-switcher.tsx", "rendered-identifier", "failure", 1],
			["apps/web/src/components/localized-tags-input.tsx", "text-prop", "props.emptyText", 1],
			["apps/web/src/components/localized-tags-input.tsx", "text-prop", "props.maximumReachedText", 1],
			["apps/web/src/components/localized-tags-input.tsx", "text-prop", "props.entryHintText", 1],
			["apps/web/src/components/lookback-selector.tsx", "rendered-identifier", "getLookbackLabel(period)", 1],
			["apps/web/src/components/measurement-scope-provision-dialog.tsx", "rendered-identifier", "labels.title", 1],
			[
				"apps/web/src/components/measurement-scope-provision-dialog.tsx",
				"rendered-identifier",
				"labels.description",
				1,
			],
			["apps/web/src/components/measurement-scope-provision-dialog.tsx", "rendered-identifier", "error", 1],
			[
				"apps/web/src/components/measurement-scope-provision-dialog.tsx",
				"rendered-identifier",
				"labels.successTitle",
				1,
			],
			["apps/web/src/components/measurement-scope-switcher.tsx", "rendered-identifier", "scopeLaneLabel(scope, t)", 1],
			["apps/web/src/components/missing-env-page.tsx", "rendered-identifier", "item.label", 1],
			["apps/web/src/components/missing-env-page.tsx", "rendered-identifier", "item.description", 1],
			["apps/web/src/components/missing-env-page.tsx", "metadata-copy", "item.label", 1],
			["apps/web/src/components/nav-main.tsx", "rendered-identifier", "group.label", 1],
			["apps/web/src/components/nav-main.tsx", "text-prop", "item.title", 1],
			["apps/web/src/components/nav-main.tsx", "rendered-identifier", "item.title", 1],
			["apps/web/src/components/opportunities-report.tsx", "rendered-identifier", "page.title", 1],
			["apps/web/src/components/opportunities-report.tsx", "rendered-identifier", "o.title", 1],
			["apps/web/src/components/opportunities-report.tsx", "rendered-identifier", "t.label", 1],
			["apps/web/src/components/page-header.tsx", "rendered-identifier", "title", 1],
			["apps/web/src/components/page-header.tsx", "rendered-identifier", "subtitle", 1],
			["apps/web/src/components/progress-bar-chart.tsx", "rendered-identifier", "item.label", 1],
			["apps/web/src/components/progress-bar-chart.tsx", "rendered-identifier", "item.label", 2],
			["apps/web/src/components/progress-bar-chart.tsx", "rendered-identifier", "label", 1],
			["apps/web/src/components/progress-bar-chart.tsx", "rendered-identifier", "item.subtitle", 1],
			["apps/web/src/components/prompt-chart-print.tsx", "rendered-identifier", "badgeLabel", 1],
			["apps/web/src/components/prompt-order-dropdown.tsx", "text-prop", "label", 1],
			["apps/web/src/components/prompt-wizard.tsx", "text-prop", "placeholder", 1],
			["apps/web/src/components/prompt-wizard.tsx", "text-prop", "placeholder", 2],
			["apps/web/src/components/prompt-wizard.tsx", "rendered-identifier", "brandNameLabel", 1],
			["apps/web/src/components/prompt-wizard.tsx", "text-prop", "brandNameLabel", 1],
			["apps/web/src/components/prompt-wizard.tsx", "rendered-identifier", "websiteLabel", 1],
			["apps/web/src/components/prompt-wizard.tsx", "text-prop", "websiteLabel", 1],
			["apps/web/src/components/prompt-wizard.tsx", "rendered-identifier", "additionalDomainsLabel", 1],
			["apps/web/src/components/prompt-wizard.tsx", "rendered-identifier", "aliasesLabel", 1],
			["apps/web/src/components/prompts-display.tsx", "text-prop", "pageTitle", 1],
			["apps/web/src/components/prompts-display.tsx", "text-prop", "pageDescription", 1],
			["apps/web/src/components/prompts-editor.tsx", "rendered-identifier", "pageTitle", 1],
			["apps/web/src/components/prompts-editor.tsx", "rendered-identifier", "pageDescription", 1],
			["apps/web/src/components/response-snapshot-panel.tsx", "rendered-identifier", "error", 1],
			["apps/web/src/components/sampling/overseas-run-now-dialog.tsx", "rendered-identifier", "label", 1],
			["apps/web/src/components/sampling/sampling-batch-create-dialog.tsx", "rendered-identifier", "target.label", 1],
			["apps/web/src/components/sampling/sampling-batch-create-dialog.tsx", "rendered-identifier", "target.label", 2],
			["apps/web/src/components/sampling/sampling-run-now-dialog.tsx", "metadata-copy", "readinessLabel(status)", 1],
			["apps/web/src/components/sampling/sampling-run-now-dialog.tsx", "rendered-identifier", "label", 1],
			["apps/web/src/components/sampling/sampling-task-workbench.tsx", "rendered-identifier", "task.targetLabel", 1],
			["apps/web/src/components/sampling/sampling-task-workbench.tsx", "rendered-identifier", "label", 1],
			["apps/web/src/components/site-header.tsx", "rendered-identifier", "pageName", 1],
			["apps/web/src/components/site-header.tsx", "rendered-identifier", "pageName", 2],
			["apps/web/src/components/site-header.tsx", "rendered-identifier", "platformContextLabel", 1],
			["apps/web/src/components/trend-chart.tsx", "rendered-identifier", "label", 1],
			["packages/ui/src/components/sidebar.tsx", "text-prop", "ariaLabel", 1],
			["packages/ui/src/components/sidebar.tsx", "text-prop", "ariaLabel", 2],
			["packages/ui/src/components/sidebar.tsx", "text-prop", "title", 1],
			["packages/ui/src/components/tags-input.tsx", "text-prop", "ariaLabel", 1],
			["packages/ui/src/components/tags-input.tsx", "text-prop", "removeTagLabel(v)", 1],
			["packages/ui/src/components/tags-input.tsx", "rendered-identifier", "opt.label", 1],
		] as const
	).map(([file, kind, value, occurrence]) => ({
		file,
		kind,
		value,
		occurrence,
		category: "localized-key" as const,
		reason: "Exact dynamic value is supplied by a localized catalog-backed UI boundary.",
	})),
	...(
		[
			["apps/web/src/routes/_authed/accept-invitation/$invitationId.tsx", "rendered-identifier", "acceptError", 1],
			["apps/web/src/routes/_authed/admin/access.tsx", "rendered-identifier", "value.brandName", 1],
			["apps/web/src/routes/_authed/admin/access.tsx", "rendered-identifier", "value.email", 1],
			["apps/web/src/routes/_authed/admin/access.tsx", "rendered-identifier", "value.temporaryPassword", 1],
			["apps/web/src/routes/_authed/admin/access.tsx", "rendered-identifier", "workspace.name", 1],
			["apps/web/src/routes/_authed/admin/access.tsx", "rendered-identifier", "entry.name", 1],
			["apps/web/src/routes/_authed/admin/access.tsx", "rendered-identifier", "entry.email", 1],
			["apps/web/src/routes/_authed/admin/index.tsx", "rendered-identifier", "added", 1],
			["apps/web/src/routes/_authed/admin/index.tsx", "rendered-identifier", "removed", 1],
			["apps/web/src/routes/_authed/admin/index.tsx", "rendered-identifier", "brand.name", 1],
			["apps/web/src/routes/_authed/admin/index.tsx", "rendered-identifier", "brand.website", 1],
			["apps/web/src/routes/_authed/admin/index.tsx", "rendered-identifier", "brand.activePrompts", 1],
			[
				"apps/web/src/routes/_authed/admin/index.tsx",
				"rendered-identifier",
				"formatNumber(brand.promptRuns7Days || 0)",
				1,
			],
			[
				"apps/web/src/routes/_authed/admin/index.tsx",
				"rendered-identifier",
				"formatNumber(brand.promptRuns30Days || 0)",
				1,
			],
			[
				"apps/web/src/routes/_authed/admin/index.tsx",
				"rendered-identifier",
				"formatDate(new Date(brand.lastPromptRunAt))",
				1,
			],
			[
				"apps/web/src/routes/_authed/admin/index.tsx",
				"rendered-identifier",
				"formatDelayHours(currentDelayHours, locale)",
				1,
			],
			["apps/web/src/routes/_authed/admin/sampling/index.tsx", "rendered-identifier", "brand.name", 1],
			["apps/web/src/routes/_authed/admin/sampling/index.tsx", "rendered-identifier", "scope.name", 1],
			["apps/web/src/routes/_authed/admin/sampling/index.tsx", "rendered-identifier", "scope.market", 1],
			["apps/web/src/routes/_authed/admin/sampling/index.tsx", "rendered-identifier", "scope.locale", 1],
			["apps/web/src/routes/_authed/admin/sampling/index.tsx", "rendered-identifier", "icon", 1],
			["apps/web/src/routes/_authed/admin/sampling/index.tsx", "rendered-identifier", "formatNumber(value)", 1],
			["apps/web/src/routes/_authed/admin/sampling/index.tsx", "rendered-identifier", "value", 1],
			["apps/web/src/routes/_authed/admin/tools.tsx", "rendered-identifier", "result.brandName", 1],
			["apps/web/src/routes/_authed/admin/tools.tsx", "rendered-identifier", "c.name", 1],
			["apps/web/src/routes/_authed/admin/tools.tsx", "rendered-identifier", 'c.domains.join(", ")', 1],
			["apps/web/src/routes/_authed/admin/tools.tsx", "rendered-identifier", "p.prompt", 1],
			["apps/web/src/routes/_authed/admin/tools.tsx", "rendered-identifier", "tag", 1],
			["apps/web/src/routes/_authed/admin/tools.tsx", "rendered-identifier", "value", 1],
			["apps/web/src/routes/_authed/admin/tools.tsx", "rendered-identifier", "it", 1],
			["apps/web/src/routes/_authed/admin/workflows.tsx", "rendered-identifier", "formatNumber(stats.created)", 1],
			["apps/web/src/routes/_authed/admin/workflows.tsx", "rendered-identifier", "formatNumber(stats.active)", 1],
			["apps/web/src/routes/_authed/admin/workflows.tsx", "rendered-identifier", "formatNumber(stats.retry)", 1],
			["apps/web/src/routes/_authed/admin/workflows.tsx", "rendered-identifier", "formatNumber(stats.completed)", 1],
			["apps/web/src/routes/_authed/admin/workflows.tsx", "rendered-identifier", "formatNumber(stats.failed)", 1],
			["apps/web/src/routes/_authed/admin/workflows.tsx", "rendered-identifier", "formatNumber(stats.totalPending)", 1],
			["apps/web/src/routes/_authed/admin/workflows.tsx", "rendered-identifier", "lastRunText", 1],
			["apps/web/src/routes/_authed/admin/workflows.tsx", "jsx-text", "(+", 1],
			[
				"apps/web/src/routes/_authed/admin/workflows.tsx",
				"rendered-identifier",
				"formatDuration(status.overdueByMs, locale)",
				1,
			],
			["apps/web/src/routes/_authed/admin/workflows.tsx", "rendered-identifier", "lastRunText", 2],
			["apps/web/src/routes/_authed/admin/workflows.tsx", "rendered-identifier", "job.data?.promptId", 1],
			[
				"apps/web/src/routes/_authed/admin/workflows.tsx",
				"rendered-identifier",
				'formatDate(new Date(job.finishedOn), { dateStyle: "medium", timeStyle: "medium" })',
				1,
			],
			["apps/web/src/routes/_authed/admin/workflows.tsx", "rendered-identifier", "brand.brandName", 1],
			["apps/web/src/routes/_authed/admin/workflows.tsx", "rendered-identifier", "brand.website", 1],
			["apps/web/src/routes/_authed/admin/workflows.tsx", "rendered-identifier", "brand.enabledPrompts", 1],
			["apps/web/src/routes/_authed/admin/workflows.tsx", "rendered-identifier", "brand.totalPrompts", 1],
			[
				"apps/web/src/routes/_authed/admin/workflows.tsx",
				"rendered-identifier",
				"formatDuration(brand.runFrequencyMs, locale)",
				1,
			],
			["apps/web/src/routes/_authed/admin/workflows.tsx", "rendered-identifier", "scheduleHealth", 1],
			["apps/web/src/routes/_authed/admin/workflows.tsx", "rendered-identifier", "model", 1],
			["apps/web/src/routes/_authed/admin/workflows.tsx", "text-prop", "prompt.promptValue", 1],
			["apps/web/src/routes/_authed/admin/workflows.tsx", "rendered-identifier", "prompt.promptValue", 1],
			["apps/web/src/routes/_authed/admin/workflows.tsx", "rendered-identifier", "data.summary.percentOnSchedule", 1],
			[
				"apps/web/src/routes/_authed/admin/workflows.tsx",
				"rendered-identifier",
				"formatNumber(data.summary.totalOnSchedule)",
				1,
			],
			["apps/web/src/routes/_authed/admin/workflows.tsx", "rendered-identifier", "overdueBreakdown.severe", 1],
			[
				"apps/web/src/routes/_authed/admin/workflows.tsx",
				"rendered-identifier",
				"formatNumber(data.summary.totalBrands)",
				1,
			],
			["apps/web/src/routes/_authed/app/$brand/index.tsx", "rendered-identifier", "value", 1],
			["apps/web/src/routes/_authed/app/$brand/index.tsx", "rendered-identifier", "tooltip", 1],
			["apps/web/src/routes/_authed/app/$brand/index.tsx", "rendered-identifier", "tooltip", 2],
			["apps/web/src/routes/_authed/app/$brand/index.tsx", "rendered-identifier", "formatNumber(value)", 1],
			["apps/web/src/routes/_authed/app/$brand/index.tsx", "rendered-identifier", "getMessage()", 1],
			["apps/web/src/routes/_authed/app/$brand/index.tsx", "rendered-identifier", "formatNumber(totalPrompts)", 1],
			[
				"apps/web/src/routes/_authed/app/$brand/opportunities.tsx",
				"rendered-identifier",
				'opportunityEmptyMessage(data?.reason ?? "insufficient-data", locale)',
				1,
			],
			["apps/web/src/routes/_authed/app/$brand/opportunities.tsx", "rendered-identifier", "content", 1],
			["apps/web/src/routes/_authed/app/$brand/opportunities.tsx", "rendered-identifier", "children", 1],
			["apps/web/src/routes/_authed/app/$brand/prompts/$promptId.tsx", "rendered-identifier", "promptMeta?.value", 1],
			[
				"apps/web/src/routes/_authed/app/$brand/prompts/$promptId.tsx",
				"rendered-identifier",
				'formatDate(new Date(promptMeta.nextRunAt), { month: "short", day: "numeric", hour: "numeric", minute: "2-digit", })',
				1,
			],
			["apps/web/src/routes/_authed/app/$brand/prompts/$promptId.tsx", "rendered-identifier", "tag", 1],
			["apps/web/src/routes/_authed/app/$brand/prompts/$promptId.tsx", "rendered-identifier", "tag", 2],
			["apps/web/src/routes/_authed/app/$brand/prompts/$promptId.tsx", "metadata-copy", "stat.name", 1],
			["apps/web/src/routes/_authed/app/$brand/prompts/$promptId.tsx", "text-prop", "fanoutTooltip", 1],
			["apps/web/src/routes/_authed/app/$brand/prompts/$promptId.tsx", "rendered-identifier", "fanoutTooltip", 1],
			[
				"apps/web/src/routes/_authed/app/$brand/prompts/$promptId.tsx",
				"rendered-identifier",
				"getModelDisplayName(run.model)",
				1,
			],
			["apps/web/src/routes/_authed/app/$brand/prompts/$promptId.tsx", "rendered-identifier", "run.version", 1],
			[
				"apps/web/src/routes/_authed/app/$brand/prompts/$promptId.tsx",
				"rendered-identifier",
				'formatDate(new Date(run.observedAt), { dateStyle: "medium", timeStyle: "short" })',
				1,
			],
			["apps/web/src/routes/_authed/app/$brand/prompts/$promptId.tsx", "rendered-identifier", "query", 1],
			["apps/web/src/routes/_authed/app/$brand/prompts/$promptId.tsx", "rendered-identifier", "brandName", 1],
			["apps/web/src/routes/_authed/app/$brand/prompts/$promptId.tsx", "rendered-identifier", "competitor", 1],
			["apps/web/src/routes/_authed/app/$brand/prompts/$promptId.tsx", "rendered-identifier", "run.answerText", 1],
			["apps/web/src/routes/_authed/app/$brand/query-fan-out.tsx", "rendered-identifier", "content", 1],
			["apps/web/src/routes/_authed/app/$brand/query-fan-out.tsx", "rendered-identifier", "tip", 1],
			["apps/web/src/routes/_authed/app/$brand/query-fan-out.tsx", "rendered-identifier", "value", 1],
			[
				"apps/web/src/routes/_authed/app/$brand/query-fan-out.tsx",
				"rendered-identifier",
				"getModelDisplayName(m.model)",
				1,
			],
			[
				"apps/web/src/routes/_authed/app/$brand/query-fan-out.tsx",
				"rendered-identifier",
				"formatNumber(m.exposedQueryRuns)",
				1,
			],
			[
				"apps/web/src/routes/_authed/app/$brand/query-fan-out.tsx",
				"rendered-identifier",
				"getModelDisplayName(m.model)",
				2,
			],
			["apps/web/src/routes/_authed/app/$brand/query-fan-out.tsx", "rendered-identifier", "formatNumber(m.unknown)", 1],
			["apps/web/src/routes/_authed/app/$brand/query-fan-out.tsx", "rendered-identifier", "message", 1],
			["apps/web/src/routes/_authed/app/$brand/query-fan-out.tsx", "text-prop", "p.promptValue", 1],
			["apps/web/src/routes/_authed/app/$brand/query-fan-out.tsx", "rendered-identifier", "p.promptValue", 1],
			[
				"apps/web/src/routes/_authed/app/$brand/query-fan-out.tsx",
				"rendered-identifier",
				"formatNumber(p.totalQueries)",
				1,
			],
			[
				"apps/web/src/routes/_authed/app/$brand/query-fan-out.tsx",
				"rendered-identifier",
				"formatNumber(p.avgPerExecution)",
				1,
			],
			["apps/web/src/routes/_authed/app/$brand/query-fan-out.tsx", "text-prop", "q.query", 1],
			["apps/web/src/routes/_authed/app/$brand/query-fan-out.tsx", "rendered-identifier", "q.query", 1],
			["apps/web/src/routes/_authed/app/$brand/query-fan-out.tsx", "rendered-identifier", "formatNumber(q.prompts)", 1],
			["apps/web/src/routes/_authed/app/$brand/query-fan-out.tsx", "rendered-identifier", "formatNumber(q.runs)", 1],
			["apps/web/src/routes/_authed/app/$brand/query-fan-out.tsx", "text-prop", "p.promptValue", 2],
			["apps/web/src/routes/_authed/app/$brand/query-fan-out.tsx", "rendered-identifier", "p.promptValue", 2],
			["apps/web/src/routes/_authed/app/$brand/query-fan-out.tsx", "rendered-identifier", "formatNumber(p.runs)", 1],
			["apps/web/src/routes/_authed/app/$brand/settings/members.tsx", "rendered-identifier", "member.name", 1],
			["apps/web/src/routes/_authed/app/$brand/settings/members.tsx", "rendered-identifier", "member.email", 1],
			["apps/web/src/routes/_authed/app/$brand/settings/members.tsx", "rendered-identifier", "invitation.email", 1],
			[
				"apps/web/src/routes/_authed/app/$brand/share-of-voice.tsx",
				"rendered-identifier",
				"formatNumber(currentShare)",
				1,
			],
			["apps/web/src/routes/_authed/app/$brand/share-of-voice.tsx", "rendered-identifier", "e.name", 1],
			[
				"apps/web/src/routes/_authed/app/$brand/share-of-voice.tsx",
				"rendered-identifier",
				"formatNumber(e.mentions)",
				1,
			],
			[
				"apps/web/src/routes/_authed/app/$brand/share-of-voice.tsx",
				"rendered-identifier",
				"formatNumber(Math.round(e.share * 100))",
				1,
			],
			[
				"apps/web/src/routes/_authed/app/$brand/share-of-voice.tsx",
				"rendered-identifier",
				"formatNumber(e.prompts)",
				1,
			],
			["apps/web/src/routes/_authed/app/$brand/share-of-voice.tsx", "rendered-identifier", "content", 1],
			["apps/web/src/routes/_authed/app/$brand.tsx", "metadata-copy", "`${brandName} · ${appName}`", 1],
			["apps/web/src/routes/_authed/app/$brand.tsx", "metadata-copy", "appName", 1],
			["apps/web/src/routes/_authed/app/index.tsx", "rendered-identifier", "org.name", 1],
			["apps/web/src/routes/_authed/app/new.tsx", "text-prop", "example.com", 1],
			["apps/web/src/routes/__root.tsx", "metadata-copy", "appName", 1],
			["apps/web/src/routes/__root.tsx", "metadata-copy", "appName", 2],
			["apps/web/src/routes/__root.tsx", "metadata-copy", "ogLocale", 1],
			["apps/web/src/routes/__root.tsx", "metadata-copy", "appUrl", 1],
			["apps/web/src/routes/__root.tsx", "metadata-copy", "ogLogo", 1],
			["apps/web/src/components/base-chart-print.tsx", "rendered-identifier", "payload.value", 1],
			["apps/web/src/components/base-chart-print.tsx", "rendered-identifier", "formatNumber(visibility!)", 1],
			["apps/web/src/components/base-chart.tsx", "metadata-copy", "brand.name", 1],
			["apps/web/src/components/base-chart.tsx", "metadata-copy", "competitor.name", 1],
			["apps/web/src/components/base-chart.tsx", "rendered-identifier", "formatNumber(visibility!)", 1],
			["apps/web/src/components/base-chart.tsx", "rendered-identifier", "name", 1],
			["apps/web/src/components/base-chart.tsx", "rendered-identifier", "formatNumber(Number(value))", 1],
			["apps/web/src/components/base-chart.tsx", "rendered-identifier", "formattedDate", 1],
			["apps/web/src/components/base-chart.tsx", "rendered-identifier", "item.dataKey", 1],
			["apps/web/src/components/base-chart.tsx", "rendered-identifier", "formatNumber(Number(item.value))", 1],
			["apps/web/src/components/cached-prompt-chart.tsx", "rendered-identifier", "exportPortal", 1],
			["apps/web/src/components/cached-prompt-chart.tsx", "rendered-identifier", "exportPortal", 2],
			["apps/web/src/components/chart-export-preview.tsx", "text-prop", "promptName", 1],
			["apps/web/src/components/chart-export-preview.tsx", "rendered-identifier", "promptName", 1],
			["apps/web/src/components/chart-export-preview.tsx", "rendered-identifier", "formatNumber(visibility)", 1],
			["apps/web/src/components/chart-export-preview.tsx", "rendered-identifier", "name", 1],
			["apps/web/src/components/chart-export-preview.tsx", "rendered-identifier", "domain", 1],
			["apps/web/src/components/chart-footer.tsx", "rendered-identifier", "children", 1],
			["apps/web/src/components/citations/content-gaps-card.tsx", "rendered-identifier", "prompt.value", 1],
			["apps/web/src/components/citations/google-shopping-card.tsx", "rendered-identifier", "p.value", 1],
			["apps/web/src/components/citations/google-shopping-card.tsx", "rendered-identifier", "formatNumber(p.count)", 1],
			["apps/web/src/components/citations/google-shopping-card.tsx", "rendered-identifier", "p.value", 2],
			["apps/web/src/components/citations/google-shopping-card.tsx", "rendered-identifier", "formatNumber(p.count)", 2],
			[
				"apps/web/src/components/citations/google-shopping-card.tsx",
				"rendered-identifier",
				"formatNumber(productCounts[key])",
				1,
			],
			["apps/web/src/components/citations/google-shopping-card.tsx", "rendered-identifier", "product.name", 1],
			[
				"apps/web/src/components/citations/google-shopping-card.tsx",
				"rendered-identifier",
				"product.competitorName",
				1,
			],
			[
				"apps/web/src/components/citations/google-shopping-card.tsx",
				"rendered-identifier",
				"formatNumber(product.count)",
				1,
			],
			["apps/web/src/components/citations/google-shopping-card.tsx", "rendered-identifier", "q.query", 1],
			["apps/web/src/components/citations/google-shopping-card.tsx", "rendered-identifier", "formatNumber(q.count)", 1],
			["apps/web/src/components/citations/recent-changes-card.tsx", "rendered-identifier", "icon", 1],
			["apps/web/src/components/citations/recent-changes-card.tsx", "rendered-identifier", "inner", 1],
			["apps/web/src/components/citations/reddit-card.tsx", "rendered-identifier", "sub.name", 1],
			["apps/web/src/components/citations/reddit-card.tsx", "rendered-identifier", "formatNumber(sub.count)", 1],
			["apps/web/src/components/citations/reddit-card.tsx", "rendered-identifier", "formatUrlForDisplay(u.url)", 1],
			["apps/web/src/components/citations/reddit-card.tsx", "rendered-identifier", "formatNumber(u.count)", 1],
			["apps/web/src/components/citations/stats-cards.tsx", "rendered-identifier", "tooltip", 1],
			["apps/web/src/components/citations/stats-cards.tsx", "rendered-identifier", "value", 1],
			["apps/web/src/components/citations/top-domains-card.tsx", "metadata-copy", "domain.domain", 1],
			[
				"apps/web/src/components/citations/top-urls-card.tsx",
				"rendered-identifier",
				"extractFilenameFromUrl(citation.url)",
				1,
			],
			["apps/web/src/components/citations/top-urls-card.tsx", "rendered-identifier", "domainPart", 1],
			["apps/web/src/components/citations/top-urls-card.tsx", "rendered-identifier", "formatNumber(citation.count)", 1],
			["apps/web/src/components/citations/track-domain-popover.tsx", "rendered-identifier", "brandName", 1],
			["apps/web/src/components/citations/track-domain-popover.tsx", "rendered-identifier", "c.name", 1],
			["apps/web/src/components/citations/trend-area-chart.tsx", "metadata-copy", "k", 1],
			["apps/web/src/components/citations/trend-area-chart.tsx", "rendered-identifier", "tooltip", 1],
			["apps/web/src/components/citations/trend-area-chart.tsx", "rendered-identifier", "formattedDate", 1],
			["apps/web/src/components/citations/trend-area-chart.tsx", "rendered-identifier", "r.k", 1],
			["apps/web/src/components/citations/trend-area-chart.tsx", "rendered-identifier", "formatNumber(r.value)", 1],
			["apps/web/src/components/col-head.tsx", "rendered-identifier", "tip", 1],
			["apps/web/src/components/competitors-editor.tsx", "rendered-identifier", "competitor.name", 1],
			[
				"apps/web/src/components/competitors-editor.tsx",
				"rendered-identifier",
				"competitor.domains.filter(Boolean)[0]",
				1,
			],
			["apps/web/src/components/customer-programs-view.tsx", "rendered-identifier", "program.name", 1],
			["apps/web/src/components/customer-programs-view.tsx", "rendered-identifier", "program.key", 1],
			["apps/web/src/components/customer-programs-view.tsx", "rendered-identifier", "program.market", 1],
			["apps/web/src/components/customer-programs-view.tsx", "rendered-identifier", "program.locale", 1],
			["apps/web/src/components/customer-programs-view.tsx", "rendered-identifier", "program.timezone", 1],
			[
				"apps/web/src/components/customer-programs-view.tsx",
				"rendered-identifier",
				"evaluationLane(program.samplingEvaluationRole, t)",
				1,
			],
			["apps/web/src/components/fanout-sections.tsx", "rendered-identifier", "children", 1],
			["apps/web/src/components/fanout-sections.tsx", "rendered-identifier", "slice.text", 1],
			[
				"apps/web/src/components/fanout-sections.tsx",
				"rendered-identifier",
				'modelCounts.map((mc) => `${formatNumber(mc.count)}× ${getModelDisplayName(mc.model)}`).join(" · ")',
				1,
			],
			["apps/web/src/components/fanout-sections.tsx", "rendered-identifier", "formatNumber(variation.count)", 1],
			["apps/web/src/components/fanout-sections.tsx", "metadata-copy", "w.word", 1],
			[
				"apps/web/src/components/fanout-sections.tsx",
				"rendered-identifier",
				'formatNumber(w.share / 100, { style: "percent", maximumFractionDigits: 0 })',
				1,
			],
			["apps/web/src/components/filter-bar.tsx", "rendered-identifier", "icon", 1],
			["apps/web/src/components/filter-bar.tsx", "rendered-identifier", "badgeCount", 1],
			["apps/web/src/components/filter-bar.tsx", "rendered-identifier", "iconForModel(model)", 1],
			["apps/web/src/components/filter-bar.tsx", "rendered-identifier", "tag", 1],
			["apps/web/src/components/filter-bar.tsx", "rendered-identifier", "extraControls", 1],
			["apps/web/src/components/filtered-list-shell.tsx", "rendered-identifier", "filterSectionExtras", 1],
			["apps/web/src/components/filtered-list-shell.tsx", "rendered-identifier", "body", 1],
			["apps/web/src/components/full-page-card.tsx", "rendered-identifier", "capability", 1],
			["apps/web/src/components/full-page-card.tsx", "rendered-identifier", "children", 1],
			["apps/web/src/components/full-page-card.tsx", "rendered-identifier", "customBackButton", 1],
			["apps/web/src/components/full-page-card.tsx", "rendered-identifier", "backButtonText", 1],
			["apps/web/src/components/logo.tsx", "text-prop", "name", 1],
			["apps/web/src/components/logo.tsx", "text-prop", "name", 2],
			["apps/web/src/components/logo.tsx", "rendered-identifier", "name", 1],
			["apps/web/src/components/measurement-scope-provision-dialog.tsx", "rendered-identifier", "labels.trigger", 1],
			["apps/web/src/components/measurement-scope-provision-dialog.tsx", "rendered-identifier", "success", 1],
			["apps/web/src/components/measurement-scope-provision-dialog.tsx", "rendered-identifier", "labels.submit", 1],
			["apps/web/src/components/measurement-scope-switcher.tsx", "rendered-identifier", "scope.name", 1],
			["apps/web/src/components/measurement-scope-switcher.tsx", "rendered-identifier", "scope.market", 1],
			["apps/web/src/components/measurement-scope-switcher.tsx", "rendered-identifier", "scope.locale", 1],
			["apps/web/src/components/measurement-scope-switcher.tsx", "rendered-identifier", "scope.timezone", 1],
			["apps/web/src/components/missing-env-page.tsx", "rendered-identifier", "localHint", 1],
			["apps/web/src/components/nav-app-info.tsx", "rendered-identifier", "__APP_VERSION__", 1],
			["apps/web/src/components/nav-user.tsx", "text-prop", "displayName", 1],
			["apps/web/src/components/nav-user.tsx", "rendered-identifier", "displayName", 1],
			["apps/web/src/components/nav-user.tsx", "text-prop", "displayName", 2],
			["apps/web/src/components/nav-user.tsx", "rendered-identifier", "displayName", 2],
			["apps/web/src/components/nav-user.tsx", "rendered-identifier", "user.email", 1],
			["apps/web/src/components/opportunities-generation-control.tsx", "rendered-identifier", "brand.name", 1],
			["apps/web/src/components/opportunities-generation-control.tsx", "rendered-identifier", "scope.name", 1],
			["apps/web/src/components/opportunities-generation-control.tsx", "rendered-identifier", "scope.market", 1],
			["apps/web/src/components/opportunities-generation-control.tsx", "rendered-identifier", "scope.locale", 1],
			["apps/web/src/components/opportunities-report.tsx", "rendered-identifier", "item", 1],
			["apps/web/src/components/opportunities-report.tsx", "rendered-identifier", "prompt.text", 1],
			["apps/web/src/components/opportunities-report.tsx", "rendered-identifier", "prompt.text", 2],
			["apps/web/src/components/opportunities-report.tsx", "rendered-identifier", "page.domain", 1],
			["apps/web/src/components/opportunities-report.tsx", "rendered-identifier", "page.domain", 2],
			["apps/web/src/components/opportunities-report.tsx", "rendered-identifier", "children", 1],
			["apps/web/src/components/opportunities-report.tsx", "rendered-identifier", "o.why", 1],
			[
				"apps/web/src/components/opportunities-report.tsx",
				"rendered-identifier",
				"formatNumber(outputLanguage, t.count)",
				1,
			],
			[
				"apps/web/src/components/opportunities-report.tsx",
				"rendered-identifier",
				"formatNumber(outputLanguage, opps.length)",
				1,
			],
			["apps/web/src/components/page-header.tsx", "rendered-identifier", "infoContent", 1],
			["apps/web/src/components/page-header.tsx", "rendered-identifier", "children", 1],
			["apps/web/src/components/page-header.tsx", "rendered-identifier", "children", 2],
			["apps/web/src/components/progress-bar-chart.tsx", "rendered-identifier", "item.tooltip", 1],
			["apps/web/src/components/progress-bar-chart.tsx", "rendered-identifier", "item.action", 1],
			["apps/web/src/components/progress-bar-chart.tsx", "rendered-identifier", "displayValue(item.count)", 1],
			["apps/web/src/components/progress-bar-chart.tsx", "rendered-identifier", "item.suffix", 1],
			["apps/web/src/components/prompt-chart-print.tsx", "rendered-identifier", "promptName", 1],
			["apps/web/src/components/prompt-chart-print.tsx", "rendered-identifier", "message", 1],
			["apps/web/src/components/prompt-chart-print.tsx", "rendered-identifier", "promptName", 2],
			["apps/web/src/components/prompt-chart-print.tsx", "rendered-identifier", "promptName", 3],
			["apps/web/src/components/prompt-chart-print.tsx", "rendered-identifier", "formatNumber(badgeValue)", 1],
			["apps/web/src/components/response-snapshot-panel.tsx", "rendered-identifier", "channel", 1],
			[
				"apps/web/src/components/response-snapshot-panel.tsx",
				"rendered-identifier",
				"snapshot.visualEvidence.sha256",
				1,
			],
			["apps/web/src/components/response-snapshot-panel.tsx", "rendered-identifier", "snapshot.htmlSha256", 1],
			["apps/web/src/components/response-snapshot-panel.tsx", "rendered-identifier", "snapshot.jsonSha256", 1],
			["apps/web/src/components/sampling/browser-runner-device-list.tsx", "rendered-identifier", "brand.name", 1],
			["apps/web/src/components/sampling/browser-runner-device-list.tsx", "rendered-identifier", "pairing.code", 1],
			[
				"apps/web/src/components/sampling/browser-runner-device-list.tsx",
				"rendered-identifier",
				"device.displayName",
				1,
			],
			["apps/web/src/components/sampling/browser-runner-device-list.tsx", "jsx-text", "· Chrome", 1],
			[
				"apps/web/src/components/sampling/browser-runner-device-list.tsx",
				"rendered-identifier",
				"device.browserVersion",
				1,
			],
			[
				"apps/web/src/components/sampling/browser-runner-device-list.tsx",
				"rendered-identifier",
				"SURFACE_LABELS[surface]",
				1,
			],
			[
				"apps/web/src/components/sampling/browser-runner-device-list.tsx",
				"template-prose",
				'`${t(READINESS_LABELS[readiness.status])} · ${t("sampling.device.active", { count: formatNumber(readiness.activeConcurrency) })}`',
				1,
			],
			[
				"apps/web/src/components/sampling/browser-runner-extension-install.tsx",
				"rendered-identifier",
				"metadata.sha256",
				1,
			],
			["apps/web/src/components/sampling/overseas-run-now-dialog.tsx", "rendered-identifier", "program.name", 1],
			["apps/web/src/components/sampling/sampling-batch-card.tsx", "rendered-identifier", "batch.name", 1],
			["apps/web/src/components/sampling/sampling-batch-card.tsx", "rendered-identifier", "batch.scopeName", 1],
			["apps/web/src/components/sampling/sampling-batch-card.tsx", "template-prose", "` · ${batch.scopeTimezone}`", 1],
			[
				"apps/web/src/components/sampling/sampling-batch-card.tsx",
				"template-prose",
				"`${automationProgress.completed}/${automationProgress.total}`",
				1,
			],
			["apps/web/src/components/sampling/sampling-batch-card.tsx", "rendered-identifier", "needsHumanCount", 1],
			[
				"apps/web/src/components/sampling/sampling-batch-card.tsx",
				"rendered-identifier",
				"percentage(coverage.successCoverage)",
				1,
			],
			["apps/web/src/components/sampling/sampling-batch-create-dialog.tsx", "rendered-identifier", "scope.name", 1],
			["apps/web/src/components/sampling/sampling-batch-create-dialog.tsx", "rendered-identifier", "scope.market", 1],
			["apps/web/src/components/sampling/sampling-batch-create-dialog.tsx", "rendered-identifier", "scope.locale", 1],
			["apps/web/src/components/sampling/sampling-batch-create-dialog.tsx", "rendered-identifier", "scope.timezone", 1],
			["apps/web/src/components/sampling/sampling-batch-create-dialog.tsx", "rendered-identifier", "prompt.value", 1],
			[
				"apps/web/src/components/sampling/sampling-batch-create-dialog.tsx",
				"rendered-identifier",
				"target.surfaceTargetKey",
				1,
			],
			["apps/web/src/components/sampling/sampling-batch-list.tsx", "text-prop", "batch.name", 1],
			["apps/web/src/components/sampling/sampling-batch-list.tsx", "rendered-identifier", "batch.name", 1],
			["apps/web/src/components/sampling/sampling-batch-list.tsx", "rendered-identifier", "batch.id.slice(0, 8)", 1],
			["apps/web/src/components/sampling/sampling-batch-list.tsx", "rendered-identifier", "batch.scopeName", 1],
			["apps/web/src/components/sampling/sampling-batch-list.tsx", "rendered-identifier", "batch.scopeMarket", 1],
			["apps/web/src/components/sampling/sampling-batch-list.tsx", "rendered-identifier", "batch.scopeLocale", 1],
			["apps/web/src/components/sampling/sampling-batch-list.tsx", "rendered-identifier", "batch.scopeTimezone", 1],
			[
				"apps/web/src/components/sampling/sampling-batch-list.tsx",
				"rendered-identifier",
				"automationProgress.completed",
				1,
			],
			[
				"apps/web/src/components/sampling/sampling-batch-list.tsx",
				"rendered-identifier",
				"automationProgress.total",
				1,
			],
			["apps/web/src/components/sampling/sampling-batch-list.tsx", "rendered-identifier", "coverage.succeeded", 1],
			["apps/web/src/components/sampling/sampling-batch-list.tsx", "rendered-identifier", "coverage.total", 1],
			[
				"apps/web/src/components/sampling/sampling-batch-list.tsx",
				"rendered-identifier",
				"percentage(coverage.successCoverage)",
				1,
			],
			["apps/web/src/components/sampling/sampling-batch-list.tsx", "rendered-identifier", "needsHumanCount", 1],
			[
				"apps/web/src/components/sampling/sampling-batch-list.tsx",
				"rendered-identifier",
				'formatDate(new Date(batch.createdAt), { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit", })',
				1,
			],
			["apps/web/src/components/sampling/sampling-run-now-dialog.tsx", "rendered-identifier", "program.name", 1],
			[
				"apps/web/src/components/sampling/sampling-task-workbench.tsx",
				"rendered-identifier",
				"task.automation.needsHumanCode",
				1,
			],
			[
				"apps/web/src/components/sampling/sampling-task-workbench.tsx",
				"rendered-identifier",
				'formatDate(new Date(task.measurementWindowStartsAt), { timeZone: task.timezone, timeZoneName: "short", })',
				1,
			],
			[
				"apps/web/src/components/sampling/sampling-task-workbench.tsx",
				"rendered-identifier",
				'formatDate(new Date(task.measurementWindowEndsAt), { timeZone: task.timezone, timeZoneName: "short", })',
				1,
			],
			["apps/web/src/components/sampling/sampling-task-workbench.tsx", "rendered-identifier", "task.promptText", 1],
			["apps/web/src/components/sampling/sampling-task-workbench.tsx", "rendered-identifier", "item.fileName", 1],
			[
				"apps/web/src/components/sampling/sampling-task-workbench.tsx",
				"rendered-identifier",
				"formatEvidenceBytes(item.sizeBytes)",
				1,
			],
			["apps/web/src/components/sampling/sampling-task-workbench.tsx", "rendered-identifier", "item.progress", 1],
			["apps/web/src/components/sampling/sampling-task-workbench.tsx", "rendered-identifier", "artifact.sha256", 1],
			["apps/web/src/components/sampling/sampling-task-workbench.tsx", "rendered-identifier", "fileName", 1],
			["apps/web/src/components/sampling/sampling-task-workbench.tsx", "rendered-identifier", "task.market", 1],
			["apps/web/src/components/sampling/sampling-task-workbench.tsx", "rendered-identifier", "task.locale", 1],
			["apps/web/src/components/sampling/sampling-task-workbench.tsx", "rendered-identifier", "task.timezone", 1],
			[
				"apps/web/src/components/sampling/sampling-task-workbench.tsx",
				"rendered-identifier",
				'formatDate(new Date(task.measurementWindowStartsAt), { timeZone: task.timezone, dateStyle: "medium", timeStyle: "medium", })',
				1,
			],
			[
				"apps/web/src/components/sampling/sampling-task-workbench.tsx",
				"rendered-identifier",
				'formatDate(new Date(task.measurementWindowEndsAt), { timeZone: task.timezone, dateStyle: "medium", timeStyle: "medium", })',
				1,
			],
			["apps/web/src/components/sampling/sampling-task-workbench.tsx", "rendered-identifier", "value", 1],
			["apps/web/src/components/share-of-voice-donut.tsx", "rendered-identifier", "s.name", 1],
			[
				"apps/web/src/components/share-of-voice-donut.tsx",
				"rendered-identifier",
				"formatNumber(Math.round((s.value / total) * 100))",
				1,
			],
			["apps/web/src/components/site-header.tsx", "rendered-identifier", "getPageDisplayName(subPage, t)", 1],
			["apps/web/src/components/site-header.tsx", "rendered-identifier", "brandName", 1],
			["apps/web/src/components/site-header.tsx", "rendered-identifier", "brandName", 2],
			["apps/web/src/components/site-header.tsx", "rendered-identifier", "getPageDisplayName(subSegment, t)", 1],
			["apps/web/src/components/text-highlighter.tsx", "rendered-identifier", "text", 1],
			["apps/web/src/components/text-highlighter.tsx", "rendered-identifier", "seg.part", 1],
			["apps/web/src/components/text-highlighter.tsx", "rendered-identifier", "seg.part", 2],
			["apps/web/src/components/trend-chart.tsx", "rendered-identifier", "formattedDate", 1],
			["apps/web/src/components/trend-chart.tsx", "rendered-identifier", "formatNumber(value)", 1],
			["apps/web/src/components/visibility-bar.tsx", "rendered-identifier", "formatNumber(currentVisibility)", 1],
			["apps/web/src/components/word-cloud.tsx", "rendered-identifier", "it.term", 1],
			["packages/ui/src/components/sidebar.tsx", "rendered-identifier", "children", 1],
			["packages/ui/src/components/sidebar.tsx", "rendered-identifier", "children", 2],
			["packages/ui/src/components/sidebar.tsx", "rendered-identifier", "children", 3],
			["packages/ui/src/components/sidebar.tsx", "rendered-identifier", "children", 4],
			["packages/ui/src/components/sidebar.tsx", "rendered-identifier", "button", 1],
			["packages/ui/src/components/breadcrumb.tsx", "rendered-identifier", "labels.more", 1],
			["packages/ui/src/components/breadcrumb.tsx", "rendered-identifier", "label", 1],
			["packages/ui/src/components/tags-input.tsx", "rendered-identifier", "candidate", 1],
			["packages/ui/src/components/tags-input.tsx", "rendered-identifier", "opt.value", 1],
			["packages/ui/src/components/tags-input.tsx", "rendered-identifier", "validationError", 1],
		] as const
	).map(([file, kind, value, occurrence]) => ({
		file,
		kind,
		value,
		occurrence,
		category: "domain-value" as const,
		reason: "Exact domain value is rendered byte-identically; only surrounding UI chrome is localized.",
	})),
	...(
		[
			["apps/web/src/routes/__root.tsx", "metadata-copy", "#000000", 1],
			["apps/web/src/routes/__root.tsx", "metadata-copy", "DEFAULT_THEME_COLOR", 1],
			[
				"apps/web/src/routes/__root.tsx",
				"jsx-text",
				"window.clarity=window.clarity||function(){(window.clarity.q=window.clarity.q||[]).push(arguments)};",
				1,
			],
		] as const
	).map(([file, kind, value, occurrence]) => ({
		file,
		kind,
		value,
		occurrence,
		category: "machine-token" as const,
		reason: "Exact color token or executable analytics bootstrap is not translatable UI copy.",
	})),
	...(
		[
			["apps/web/src/components/citations/recent-changes-card.tsx", "metadata-copy", "citation.changes.title", 1],
			["apps/web/src/components/citations/shared.tsx", "metadata-copy", "t(CATEGORY_MESSAGE_IDS[c])", 1],
			["apps/web/src/components/citations/shared.tsx", "metadata-copy", "t(PAGE_TYPE_MESSAGE_IDS[p])", 1],
			["apps/web/src/components/customer-programs-view.tsx", "rendered-identifier", "t(laneMessageIds.scored)", 1],
			["apps/web/src/components/customer-programs-view.tsx", "rendered-identifier", "t(laneMessageIds.observation)", 1],
			["apps/web/src/components/customer-programs-view.tsx", "rendered-identifier", 't("program.lane.unassigned")', 1],
			["apps/web/src/components/sampling/sampling-run-now-dialog.tsx", "metadata-copy", "sampling.readiness.ready", 1],
			[
				"apps/web/src/components/sampling/sampling-run-now-dialog.tsx",
				"metadata-copy",
				"sampling.readiness.offlineQueue",
				1,
			],
		] as const
	).map(([file, kind, value, occurrence]) => ({
		file,
		kind,
		value,
		occurrence,
		category: "localized-key" as const,
		reason: "Exact typed bilingual catalog ID is subsequently consumed by the localized renderer.",
	})),
	...(
		[
			["packages/ui/src/components/sidebar.tsx", "jsx-text", "Sidebar", 1],
			["packages/ui/src/components/sidebar.tsx", "jsx-text", "Displays the mobile sidebar.", 1],
			["packages/ui/src/components/sidebar.tsx", "jsx-text", "Toggle Sidebar", 1],
			["packages/ui/src/components/tags-input.tsx", "jsx-text", "Select...", 1],
			["packages/ui/src/components/tags-input.tsx", "jsx-text", "No results.", 1],
			["packages/ui/src/components/tags-input.tsx", "jsx-text", "Type or paste to add a value", 1],
			["packages/ui/src/components/tags-input.tsx", "jsx-text", "Add", 1],
		] as const
	).map(([file, kind, value, occurrence]) => ({
		file,
		kind,
		value,
		occurrence,
		category: "shared-backward-compatible-default" as const,
		reason: "Exact shared-package compatibility default; audited Portal call sites supply localized copy.",
	})),
	...(
		[
			["apps/web/src/routes/__root.tsx", "metadata-copy", "`${appUrl}${ogImagePath}`", 1],
			["apps/web/src/routes/__root.tsx", "metadata-copy", "`/api/og?${ogImageParams.toString()}`", 1],
			["apps/web/src/components/citations/recent-changes-card.tsx", "rendered-identifier", "domain", 1],
			[
				"apps/web/src/components/citations/recent-changes-card.tsx",
				"rendered-identifier",
				"formatUrlForDisplay(rawUrl)",
				1,
			],
			["apps/web/src/components/citations/top-urls-card.tsx", "rendered-identifier", "citation.title", 1],
			[
				"apps/web/src/components/citations/top-urls-card.tsx",
				"rendered-identifier",
				"displayUrl.substring(domainEndIndex)",
				1,
			],
			[
				"apps/web/src/components/measurement-scope-switcher.tsx",
				"template-prose",
				"`${selected.name} | ${selected.market}/${selected.locale} | ${scopeLaneLabel(selected, t)}`",
				1,
			],
			["apps/web/src/components/opportunities-report.tsx", "metadata-copy", "opportunity.content", 1],
			["apps/web/src/components/opportunities-report.tsx", "metadata-copy", "opportunity.category.existing", 1],
			["apps/web/src/components/opportunities-report.tsx", "metadata-copy", "opportunity.category.outreach", 1],
			["apps/web/src/components/opportunities-report.tsx", "metadata-copy", "opportunity.category.social", 1],
		] as const
	).map(([file, kind, value, occurrence]) => ({
		file,
		kind,
		value,
		occurrence,
		category: "domain-value" as const,
		reason: "Exact URL, citation, artifact, or Program domain value remains byte-identical.",
	})),
	...(
		[
			["apps/web/src/routes/_authed/app/$brand/prompts/$promptId.tsx", "text-prop", "promptMeta?.value", 1],
			["apps/web/src/components/prompt-wizard.tsx", "text-prop", "data.website.trim()", 1],
			["apps/web/src/components/prompt-wizard.tsx", "text-prop", "brand?.website", 1],
			["apps/web/src/components/site-header.tsx", "text-prop", "brand?.name", 1],
		] as const
	).map(([file, kind, value, occurrence]) => ({
		file,
		kind,
		value,
		occurrence,
		category: "domain-value" as const,
		reason: "Exact Portal domain value is passed through byte-identically; only surrounding UI copy is localized.",
	})),
	...(
		[
			["apps/web/src/components/localized-tags-input.tsx", "text-prop", "props.removeTagLabel", 1],
			["apps/web/src/components/localized-tags-input.tsx", "text-prop", "props.addValueText", 1],
		] as const
	).map(([file, kind, value, occurrence]) => ({
		file,
		kind,
		value,
		occurrence,
		category: "shared-backward-compatible-default" as const,
		reason: "Exact caller-supplied compatibility override is audited at the localized Portal call site.",
	})),
];
