/**
 * Shared E2E fixture constants — the single place the seeder, auth setup, and
 * Playwright specs agree on IDs and credentials. Unlike seed.ts this module
 * has no side effects, so specs can import from it freely.
 */

// The host, credentials, and database stay hardcoded to localhost so the
// destructive seeder can never point at a production database. Only the host
// port is configurable, which lets an isolated E2E Postgres coexist with a
// developer database already listening on 5432.
const e2ePostgresPort = process.env.E2E_POSTGRES_PORT ?? "5432";
if (!/^\d{1,5}$/.test(e2ePostgresPort)) {
  throw new Error(`Invalid E2E_POSTGRES_PORT: ${e2ePostgresPort}`);
}
const parsedE2ePostgresPort = Number(e2ePostgresPort);
if (parsedE2ePostgresPort < 1 || parsedE2ePostgresPort > 65_535) {
  throw new Error(`E2E_POSTGRES_PORT is out of range: ${e2ePostgresPort}`);
}
export const DATABASE_URL =
  `postgres://postgres:postgres@localhost:${parsedE2ePostgresPort}/yonaris`;

// Must match ADMIN_API_KEYS in the CI-patched .env (.github/workflows/e2e.yaml)
// and bruno/environments/local.bru.
export const TEST_API_KEY = "test-api-key-e2e";

export const TEST_USER = {
  email: "e2e@test.local",
  password: "e2e-test-password-123",
  name: "E2E Test User",
} as const;

/**
 * A real non-platform identity provisioned by the platform administrator in
 * global setup. Its password is intentionally generated by the product's
 * one-time-credential flow, never hardcoded here.
 */
export const CUSTOMER_TEST_USER = {
  email: "stepfun-analyst@e2e.test",
  name: "StepFun E2E Analyst",
  role: "analyst",
} as const;

/** Dedicated serial identity/data for the bilingual portal smoke. */
export const LANGUAGE_SMOKE_USER = {
  email: "portal-language@e2e.test",
  password: "portal-language-password-123",
  name: "Portal Language E2E",
} as const;
export const LANGUAGE_SMOKE_ORG_ID = "portal-language-e2e-org";
export const LANGUAGE_SMOKE_BRAND_ID = "portal-language-e2e";
export const LANGUAGE_SMOKE_BRAND_NAME = "Language Smoke 原始品牌";
export const LANGUAGE_SMOKE_BRAND_WEBSITE = "https://language-smoke.example.cn/raw?market=CN";
export const LANGUAGE_SMOKE_SCOPES = {
  cn: {
    id: "00000000-0000-4000-8000-710000000001",
    key: "cn-zh-language-smoke",
    name: "中国市场 / zh-CN 原始项目",
    market: "CN",
    locale: "zh-CN",
    timezone: "Asia/Shanghai",
  },
  en: {
    id: "00000000-0000-4000-8000-710000000002",
    key: "us-en-language-smoke",
    name: "US Market / en-US Raw Program",
    market: "US",
    locale: "en-US",
    timezone: "America/New_York",
  },
} as const;
export const LANGUAGE_SMOKE_PROMPTS = {
  cn: {
    id: "00000000-0000-4000-8000-710000000011",
    value: "适合家庭出游的新能源 SUV",
    derivedQuery: "2026 北京 30万 SUV 推荐",
  },
  en: {
    id: "00000000-0000-4000-8000-710000000012",
    value: "Best family EV SUV for road trips?",
    derivedQuery: "family electric SUV range comparison",
  },
} as const;
export const LANGUAGE_SMOKE_RUNS = {
  cn: "00000000-0000-4000-8000-710000000021",
  en: "00000000-0000-4000-8000-710000000022",
} as const;

export const LANGUAGE_SMOKE_OPPORTUNITY_EVIDENCE = {
  brand: LANGUAGE_SMOKE_BRAND_NAME,
  competitor: "原始竞品 / Raw Rival",
  prompt: {
    id: LANGUAGE_SMOKE_PROMPTS.cn.id,
    text: LANGUAGE_SMOKE_PROMPTS.cn.value,
  },
  yourCitation: {
    title: `${LANGUAGE_SMOKE_BRAND_NAME} / Raw Brand Evidence`,
    domain: "language-smoke.example.cn",
    url: LANGUAGE_SMOKE_BRAND_WEBSITE,
  },
  competitorCitation: {
    title: "原始竞品 / Raw Rival",
    domain: "raw-rival.example",
    url: "https://raw-rival.example/evidence?source=language-smoke#unchanged",
  },
} as const;

export const LANGUAGE_SMOKE_OPPORTUNITIES = {
  en: {
    id: "00000000-0000-4000-8000-720000000001",
    brandId: LANGUAGE_SMOKE_BRAND_ID,
    scopeId: LANGUAGE_SMOKE_SCOPES.cn.id,
    outputLanguage: "en",
    report: {
      summary: ["English model summary: earn trusted third-party coverage."],
      opportunities: [
        {
          category: "creation",
          title: "English model opportunity: win the family EV comparison",
          why: "English model rationale: trusted citations can improve answer presence.",
          relatedPrompts: [
            {
              promptId: LANGUAGE_SMOKE_OPPORTUNITY_EVIDENCE.prompt.id,
              text: LANGUAGE_SMOKE_OPPORTUNITY_EVIDENCE.prompt.text,
            },
          ],
          yourCitations: [LANGUAGE_SMOKE_OPPORTUNITY_EVIDENCE.yourCitation],
          competitorCitations: [LANGUAGE_SMOKE_OPPORTUNITY_EVIDENCE.competitorCitation],
        },
      ],
      risks: ["English model risk: editorial placements are not guaranteed."],
    },
    model: "e2e-fixed-opportunity",
    createdAt: "2026-08-20T08:00:00.000Z",
  },
  "zh-CN": {
    id: "00000000-0000-4000-8000-720000000002",
    brandId: LANGUAGE_SMOKE_BRAND_ID,
    scopeId: LANGUAGE_SMOKE_SCOPES.cn.id,
    outputLanguage: "zh-CN",
    report: {
      summary: ["中文模型摘要：争取可信的第三方内容收录。"],
      opportunities: [
        {
          category: "creation",
          title: "中文模型机会：进入家庭新能源车对比内容",
          why: "中文模型理由：可信引用有助于提升品牌在 AI 回答中的呈现。",
          relatedPrompts: [
            {
              promptId: LANGUAGE_SMOKE_OPPORTUNITY_EVIDENCE.prompt.id,
              text: LANGUAGE_SMOKE_OPPORTUNITY_EVIDENCE.prompt.text,
            },
          ],
          yourCitations: [LANGUAGE_SMOKE_OPPORTUNITY_EVIDENCE.yourCitation],
          competitorCitations: [LANGUAGE_SMOKE_OPPORTUNITY_EVIDENCE.competitorCitation],
        },
      ],
      risks: ["中文模型风险：编辑收录无法保证。"],
    },
    model: "e2e-fixed-opportunity",
    createdAt: "2026-08-20T08:01:00.000Z",
  },
} as const;

export const LANGUAGE_SMOKE_OPPORTUNITY_STORAGE_KEY =
  `yonaris:artifact-output-language:v1:opportunities-customer:${LANGUAGE_SMOKE_BRAND_ID}:${LANGUAGE_SMOKE_SCOPES.cn.id}`;

export const STEPFUN_ORG_ID = "stepfun-e2e-org";
export const STEPFUN_BRAND_ID = "stepfun-e2e";
export const STEPFUN_BRAND_NAME = "StepFun";
export const STEPFUN_SCOPE_ID = "00000000-0000-4000-8000-510000000001";
export const STEPFUN_PROMPT_ID = "00000000-0000-0000-0000-510000000002";
export const STEPFUN_RUN_ID = "00000000-0000-0000-0000-510000000003";
export const STEPFUN_SNAPSHOT_EXPORT_DAYS_AGO = 10;
export const STEPFUN_SNAPSHOT_RUN_IDS = {
  nativeHtml: STEPFUN_RUN_ID,
  renderedFallback: "00000000-0000-0000-0000-510000000004",
  domesticBrowser: "00000000-0000-0000-0000-510000000005",
  pending: "00000000-0000-0000-0000-510000000006",
  failed: "00000000-0000-0000-0000-510000000007",
  expired: "00000000-0000-0000-0000-510000000008",
} as const;
export const STEPFUN_SNAPSHOT_IDS = {
  nativeHtml: "00000000-0000-0000-0000-610000000001",
  renderedFallback: "00000000-0000-0000-0000-610000000002",
  domesticBrowser: "00000000-0000-0000-0000-610000000003",
  pending: "00000000-0000-0000-0000-610000000004",
  failed: "00000000-0000-0000-0000-610000000005",
  expired: "00000000-0000-0000-0000-610000000006",
} as const;

export const MEMTENSOR_ORG_ID = "mentensor-e2e-org";
export const MEMTENSOR_BRAND_ID = "mentensor-e2e";
export const MEMTENSOR_BRAND_NAME = "MemTensor";
export const MEMTENSOR_SCOPE_ID = "00000000-0000-0000-0000-520000000001";
export const MEMTENSOR_PROMPT_ID = "00000000-0000-0000-0000-520000000002";
export const MEMTENSOR_RUN_ID = "00000000-0000-0000-0000-520000000003";
export const MEMTENSOR_SNAPSHOT_ID = "00000000-0000-0000-0000-620000000001";

export const TEST_BRAND_ID = "default";
export const TEST_BRAND_NAME = "Test Organization";
export const TEST_BRAND_WEBSITE = "https://example.com";
export const TEST_SCOPE_ID = "00000000-0000-0000-0000-500000000001";

export const PROMPT_IDS = {
  branded1: "00000000-0000-0000-0000-000000000001",
  branded2: "00000000-0000-0000-0000-000000000002",
  unbranded1: "00000000-0000-0000-0000-000000000003",
  branded3: "00000000-0000-0000-0000-000000000004",
  unbranded2: "00000000-0000-0000-0000-000000000005",
} as const;

export const COMPETITOR_IDS = {
  competitorA: "00000000-0000-0000-0000-100000000001",
  competitorB: "00000000-0000-0000-0000-100000000002",
} as const;

export const REPORT_IDS = {
  completed: "00000000-0000-0000-0000-300000000001",
  pending: "00000000-0000-0000-0000-300000000002",
  processing: "00000000-0000-0000-0000-300000000003",
  failed: "00000000-0000-0000-0000-300000000004",
} as const;

// Second tenant — a brand in an org the E2E user is NOT a member of.
export const NIKE_ORG_ID = "nike";
export const NIKE_BRAND_ID = "nike";
export const NIKE_SCOPE_ID = "00000000-0000-0000-0000-500000000002";
export const NIKE_PROMPT_IDS = {
  training: "00000000-0000-0000-0000-400000000001",
  lifestyle: "00000000-0000-0000-0000-400000000002",
} as const;
export const NIKE_COMPETITOR_IDS = {
  adidas: "00000000-0000-0000-0000-410000000001",
  puma: "00000000-0000-0000-0000-410000000002",
} as const;
