/**
 * Shared E2E fixture constants — the single place the seeder, auth setup, and
 * Playwright specs agree on IDs and credentials. Unlike seed.ts this module
 * has no side effects, so specs can import from it freely.
 */

// The host, credentials, and database stay hardcoded to localhost so the
// destructive seeder can never point at a production database. Only the host
// port is configurable, which lets an isolated E2E Postgres coexist with a
// developer database already listening on 5432.
const e2ePostgresPort = process.env.E2E_POSTGRES_PORT ?? "5432";
if (!/^\d{1,5}$/.test(e2ePostgresPort)) {
  throw new Error(`Invalid E2E_POSTGRES_PORT: ${e2ePostgresPort}`);
}
const parsedE2ePostgresPort = Number(e2ePostgresPort);
if (parsedE2ePostgresPort < 1 || parsedE2ePostgresPort > 65_535) {
  throw new Error(`E2E_POSTGRES_PORT is out of range: ${e2ePostgresPort}`);
}
export const DATABASE_URL =
  `postgres://postgres:postgres@localhost:${parsedE2ePostgresPort}/elmo`;

// Must match ADMIN_API_KEYS in the CI-patched .env (.github/workflows/e2e.yaml)
// and bruno/environments/local.bru.
export const TEST_API_KEY = "test-api-key-e2e";

export const TEST_USER = {
  email: "e2e@test.local",
  password: "e2e-test-password-123",
  name: "E2E Test User",
} as const;

/**
 * A real non-platform identity provisioned by the platform administrator in
 * global setup. Its password is intentionally generated by the product's
 * one-time-credential flow, never hardcoded here.
 */
export const CUSTOMER_TEST_USER = {
  email: "stepfun-analyst@e2e.test",
  name: "StepFun E2E Analyst",
  role: "analyst",
} as const;

export const STEPFUN_ORG_ID = "stepfun-e2e-org";
export const STEPFUN_BRAND_ID = "stepfun-e2e";
export const STEPFUN_BRAND_NAME = "StepFun";
export const STEPFUN_SCOPE_ID = "00000000-0000-0000-0000-510000000001";
export const STEPFUN_PROMPT_ID = "00000000-0000-0000-0000-510000000002";
export const STEPFUN_RUN_ID = "00000000-0000-0000-0000-510000000003";
export const STEPFUN_SNAPSHOT_RUN_IDS = {
  nativeHtml: STEPFUN_RUN_ID,
  renderedFallback: "00000000-0000-0000-0000-510000000004",
  domesticBrowser: "00000000-0000-0000-0000-510000000005",
  pending: "00000000-0000-0000-0000-510000000006",
  failed: "00000000-0000-0000-0000-510000000007",
  expired: "00000000-0000-0000-0000-510000000008",
} as const;
export const STEPFUN_SNAPSHOT_IDS = {
  nativeHtml: "00000000-0000-0000-0000-610000000001",
  renderedFallback: "00000000-0000-0000-0000-610000000002",
  domesticBrowser: "00000000-0000-0000-0000-610000000003",
  pending: "00000000-0000-0000-0000-610000000004",
  failed: "00000000-0000-0000-0000-610000000005",
  expired: "00000000-0000-0000-0000-610000000006",
} as const;

export const MEMTENSOR_ORG_ID = "mentensor-e2e-org";
export const MEMTENSOR_BRAND_ID = "mentensor-e2e";
export const MEMTENSOR_BRAND_NAME = "MemTensor";
export const MEMTENSOR_SCOPE_ID = "00000000-0000-0000-0000-520000000001";
export const MEMTENSOR_PROMPT_ID = "00000000-0000-0000-0000-520000000002";
export const MEMTENSOR_RUN_ID = "00000000-0000-0000-0000-520000000003";
export const MEMTENSOR_SNAPSHOT_ID = "00000000-0000-0000-0000-620000000001";

export const TEST_BRAND_ID = "default";
export const TEST_BRAND_NAME = "Test Organization";
export const TEST_BRAND_WEBSITE = "https://example.com";
export const TEST_SCOPE_ID = "00000000-0000-0000-0000-500000000001";

export const PROMPT_IDS = {
  branded1: "00000000-0000-0000-0000-000000000001",
  branded2: "00000000-0000-0000-0000-000000000002",
  unbranded1: "00000000-0000-0000-0000-000000000003",
  branded3: "00000000-0000-0000-0000-000000000004",
  unbranded2: "00000000-0000-0000-0000-000000000005",
} as const;

export const COMPETITOR_IDS = {
  competitorA: "00000000-0000-0000-0000-100000000001",
  competitorB: "00000000-0000-0000-0000-100000000002",
} as const;

export const REPORT_IDS = {
  completed: "00000000-0000-0000-0000-300000000001",
  pending: "00000000-0000-0000-0000-300000000002",
  processing: "00000000-0000-0000-0000-300000000003",
  failed: "00000000-0000-0000-0000-300000000004",
} as const;

// Second tenant — a brand in an org the E2E user is NOT a member of.
export const NIKE_ORG_ID = "nike";
export const NIKE_BRAND_ID = "nike";
export const NIKE_SCOPE_ID = "00000000-0000-0000-0000-500000000002";
export const NIKE_PROMPT_IDS = {
  training: "00000000-0000-0000-0000-400000000001",
  lifestyle: "00000000-0000-0000-0000-400000000002",
} as const;
export const NIKE_COMPETITOR_IDS = {
  adidas: "00000000-0000-0000-0000-410000000001",
  puma: "00000000-0000-0000-0000-410000000002",
} as const;
