import type { PageMeta } from "./global";
import { type DeepReadonly, deepFreeze, type FactualClaim, type Locale } from "./types";

export type ProductWorkbenchViewId = "scope" | "answer" | "sources" | "next-test";
export type ProductActivityId = "define-scope" | "observe-answer" | "inspect-evidence" | "choose-next-test";
export type ProductClaim = FactualClaim & { limitation: string };

export interface ProductWorkbenchUi {
	tabListLabel: string;
	capabilityContextLabel: string;
	illustrativeLabel: string;
	knownLabel: string;
	unknownLabel: string;
	currentSoftwareLabel: string;
	managedDeliveryLabel: string;
	verifiedEvidenceLabel: string;
	directionLabel: string;
}

export type ProductWorkbenchField =
	| { label: string; state: "known"; value: string }
	| { label: string; state: "unknown"; reason: string };

export interface ProductWorkbenchView {
	id: ProductWorkbenchViewId;
	tabLabel: string;
	title: string;
	description: string;
	status: "illustrative";
	claims: readonly ProductClaim[];
	fields: readonly ProductWorkbenchField[];
}

export interface ProductActivity {
	id: ProductActivityId;
	title: string;
	summary: string;
	claims: readonly ProductClaim[];
}

export interface ProductHomePreview {
	title: string;
	summary: string;
	evidenceLabel: string;
	limitation: string;
	claims: readonly ProductClaim[];
}

interface ProductClaimSection {
	title: string;
	claims: readonly ProductClaim[];
}

export interface ProductContent {
	meta: PageMeta;
	eyebrow: string;
	headline: string;
	currentScope: string;
	heroClaims: readonly ProductClaim[];
	heroClaimSeparator: string;
	activitiesLabel: string;
	activitiesTitle: string;
	boundaryLabel: string;
	contextLabel: string;
	workspaceBoundary: {
		title: string;
		customer: ProductClaimSection;
		yonaris: ProductClaimSection;
	};
	coverage: ProductClaimSection;
	workbench: {
		eyebrow: string;
		title: string;
		description: string;
		ui: ProductWorkbenchUi;
		views: readonly ProductWorkbenchView[];
	};
	contextLinks: {
		title: string;
		geoLabel: string;
		diagnosticLabel: string;
	};
	activities: readonly ProductActivity[];
	homePreview: ProductHomePreview;
	claims: readonly ProductClaim[];
	limitations: readonly string[];
}

const enConfiguredScope = {
	id: "product-configured-scope",
	status: "current-software",
	text: "Workspaces support brand, domain, alias, competitor, Program, and tracked-question configuration.",
	limitation: "Scope is configured per Program rather than inferred as universal market coverage.",
} as const satisfies ProductClaim;

const enConfiguredSampling = {
	id: "product-configured-sampling",
	status: "managed-delivery",
	text: "Yonaris collects configured provider samples and can operate supported consumer-surface collection.",
	limitation: "Some execution remains operator-managed and is not continuous or universally available.",
} as const satisfies ProductClaim;

const enReviewableEvidence = {
	id: "product-reviewable-evidence",
	status: "current-software",
	text: "Users can inspect sampled responses, mention metrics, configured-cohort share of voice, citations, and exposed query fan-out when available.",
	limitation:
		"A missing citation or query field describes unavailable evidence, not proof that a provider performed no search.",
} as const satisfies ProductClaim;

const enReviewedOpportunities = {
	id: "product-reviewed-opportunities",
	status: "managed-delivery",
	text: "Opportunity recommendations are generated by operators and reviewed by people before delivery.",
	limitation: "Yonaris does not autonomously remediate or publish changes.",
} as const satisfies ProductClaim;

const enHeroWorkspace = {
	id: "product-hero-workspace",
	status: "current-software",
	text: "The customer workspace exposes configured Programs and reviewable answer evidence;",
	limitation: `${enConfiguredScope.limitation} ${enReviewableEvidence.limitation}`,
} as const satisfies ProductClaim;

const enHeroOperations = {
	id: "product-hero-operations",
	status: "managed-delivery",
	text: "Yonaris currently operates some collection and reviews opportunity recommendations.",
	limitation: `${enConfiguredSampling.limitation} ${enReviewedOpportunities.limitation}`,
} as const satisfies ProductClaim;

const enCoverage = {
	id: "product-configured-coverage",
	status: "current-software",
	text: "Coverage depends on the providers and consumer surfaces configured for the Program.",
	limitation:
		"Some surfaces do not expose citations or search queries; unavailable fields do not establish that no search occurred.",
} as const satisfies ProductClaim;

const enIllustrativeScope = {
	id: "product-illustrative-scope",
	status: "illustrative",
	text: "This declared scope belongs to the fictional Northstar Materials sample shown in the workbench.",
	limitation: "The company, Program, market, and tracked question are illustrative rather than customer data.",
} as const satisfies ProductClaim;

const enIllustrativeAnswer = {
	id: "product-illustrative-answer",
	status: "illustrative",
	text: "The workbench preserves one exact fictional sampled answer with its declared surface, model, and sample time.",
	limitation: "The answer is a designed example and does not represent a live provider response or product result.",
} as const satisfies ProductClaim;

const enIllustrativeSources = {
	id: "product-illustrative-sources",
	status: "illustrative",
	text: "The fictional answer includes inspectable citations and an explicitly unknown exposed-query state.",
	limitation: "Unknown means the field was not exposed to this sample; it does not mean that a search did not occur.",
} as const satisfies ProductClaim;

const enIllustrativeNextTest = {
	id: "product-illustrative-next-test",
	status: "illustrative",
	text: "The fictional record ends with one bounded next test and a named human review owner.",
	limitation: "A next test is a reviewable hypothesis, not an automated action or a causal conclusion.",
} as const satisfies ProductClaim;

export const pageEn = {
	meta: {
		title: "Make AI market answers observable.",
		description:
			"Define a market scope, inspect sampled AI answers and their available evidence, then choose a bounded next test.",
	},
	eyebrow: "Product · Evidence workbench",
	headline: "Make AI market answers observable.",
	currentScope:
		"The customer workspace exposes configured Programs and reviewable answer evidence; Yonaris currently operates some collection and reviews opportunity recommendations.",
	heroClaims: [enHeroWorkspace, enHeroOperations],
	heroClaimSeparator: " ",
	activitiesLabel: "One evidence workflow",
	activitiesTitle: "Four activities. One declared chain of evidence.",
	boundaryLabel: "Product boundary",
	contextLabel: "Product in context",
	workspaceBoundary: {
		title: "Where the work happens today",
		customer: {
			title: "Customer workspace",
			claims: [enConfiguredScope, enReviewableEvidence],
		},
		yonaris: {
			title: "Yonaris-operated",
			claims: [enConfiguredSampling, enReviewedOpportunities],
		},
	},
	coverage: {
		title: "Coverage is declared, not assumed",
		claims: [enCoverage],
	},
	activities: [
		{
			id: "define-scope",
			title: "Define the scope",
			summary: enConfiguredScope.text,
			claims: [enConfiguredScope],
		},
		{
			id: "observe-answer",
			title: "Observe the answer",
			summary: enConfiguredSampling.text,
			claims: [enConfiguredSampling],
		},
		{
			id: "inspect-evidence",
			title: "Inspect the evidence",
			summary: enReviewableEvidence.text,
			claims: [enReviewableEvidence],
		},
		{
			id: "choose-next-test",
			title: "Choose the next test",
			summary: enReviewedOpportunities.text,
			claims: [enReviewedOpportunities],
		},
	],
	workbench: {
		eyebrow: "Fictional Program · Northstar Materials",
		title: "Follow one sample from scope to next test.",
		description:
			"This illustrative record shows how evidence can stay reviewable without pretending that the sample is live customer data.",
		ui: {
			tabListLabel: "Illustrative evidence views",
			capabilityContextLabel: "Capability context",
			illustrativeLabel: "Illustrative",
			knownLabel: "Known",
			unknownLabel: "Unknown",
			currentSoftwareLabel: "Current software",
			managedDeliveryLabel: "Managed delivery",
			verifiedEvidenceLabel: "Verified evidence",
			directionLabel: "Direction",
		},
		views: [
			{
				id: "scope",
				tabLabel: "Scope",
				title: "A declared Program boundary",
				description: "The sample starts with the market and question a reviewer actually intends to observe.",
				status: "illustrative",
				claims: [enIllustrativeScope, enConfiguredScope],
				fields: [
					{ label: "Brand", state: "known", value: "Northstar Materials · fictional company" },
					{ label: "Market", state: "known", value: "US inventory-planning software" },
					{ label: "Language", state: "known", value: "English" },
					{ label: "Timezone", state: "known", value: "America/New_York" },
					{
						label: "Tracked question",
						state: "known",
						value: "Which inventory-planning platforms are strongest for regional manufacturers?",
					},
				],
			},
			{
				id: "answer",
				tabLabel: "Answer",
				title: "One exact fictional answer",
				description: "The answer stays attached to the surface, model label, and observation time used by the example.",
				status: "illustrative",
				claims: [enIllustrativeAnswer, enConfiguredSampling],
				fields: [
					{ label: "Surface", state: "known", value: "Atlas Answer · fictional consumer surface" },
					{ label: "Model", state: "known", value: "Atlas Preview 2 · fictional model" },
					{ label: "Sampled at", state: "known", value: "14 August 2026 · 14:30 UTC · illustrative" },
					{
						label: "Exact sampled answer",
						state: "known",
						value:
							"For regional manufacturers, compare Northstar Materials for scenario planning, Quarryline for supplier collaboration, and Ledgerfield for demand forecasting. Validate data coverage and implementation support before selecting a platform.",
					},
				],
			},
			{
				id: "sources",
				tabLabel: "Sources",
				title: "Evidence, including what is unknown",
				description: "Known source fields and unavailable query evidence remain different states.",
				status: "illustrative",
				claims: [enIllustrativeSources, enReviewableEvidence],
				fields: [
					{
						label: "Citation 01",
						state: "known",
						value: "Inventory scenarios for regional manufacturers · northstar.example · fictional",
					},
					{
						label: "Citation 02",
						state: "known",
						value: "Planning platform evaluation guide · fieldmanual.example · fictional",
					},
					{
						label: "Exposed search query",
						state: "unknown",
						reason:
							"This illustrative surface did not expose a query field to the sampler; that does not establish that no search occurred.",
					},
				],
			},
			{
				id: "next-test",
				tabLabel: "Next test",
				title: "A bounded, human-reviewed next test",
				description: "The record closes with a testable editorial change rather than an automatic recommendation loop.",
				status: "illustrative",
				claims: [enIllustrativeNextTest, enReviewedOpportunities],
				fields: [
					{
						label: "Observed gap",
						state: "known",
						value: "The answer names Northstar but does not explain its regional ERP connector boundary.",
					},
					{
						label: "Bounded next test",
						state: "known",
						value: "Clarify the connector boundary on one comparison page, then repeat the same declared question set.",
					},
					{ label: "Human review", state: "known", value: "Yonaris analyst + customer market lead" },
					{
						label: "Causal effect",
						state: "unknown",
						reason: "A repeated cohort is required; this single illustrative sample cannot establish causal effect.",
					},
				],
			},
		],
	},
	contextLinks: {
		title: "Put the evidence model to work",
		geoLabel: "See the GEO workflow",
		diagnosticLabel: "Get a Free Diagnostic",
	},
	homePreview: {
		title: "From sampled answer to reviewable evidence",
		summary: enReviewableEvidence.text,
		evidenceLabel: "Illustrative evidence view",
		limitation: enReviewableEvidence.limitation,
		claims: [enReviewableEvidence, enCoverage],
	},
	claims: [enConfiguredScope, enConfiguredSampling, enReviewableEvidence, enReviewedOpportunities],
	limitations: [
		"The complete workflow is not yet public self-service onboarding.",
		"Results are sampled observations, not causal attribution, ranking guarantees, or universal coverage.",
	],
} as const satisfies ProductContent;

const zhConfiguredScope = {
	id: "product-configured-scope",
	status: "current-software",
	text: "工作区支持配置品牌、域名、别名、竞品、Program 和跟踪问题。",
	limitation: "每个 Program 都有明确范围，不代表系统自动覆盖整个市场。",
} as const satisfies ProductClaim;

const zhConfiguredSampling = {
	id: "product-configured-sampling",
	status: "managed-delivery",
	text: "Yonaris 会采集已配置服务商的样本，也可操作受支持的消费端界面采集流程。",
	limitation: "部分执行依赖运营人员，并非持续运行或适用于所有界面。",
} as const satisfies ProductClaim;

const zhReviewableEvidence = {
	id: "product-reviewable-evidence",
	status: "current-software",
	text: "用户可以检查回答样本、提及指标、指定竞品集合内的声量份额，以及可用的引用和查询改写。",
	limitation: "引用或查询字段为空，只表示证据不可用，不能据此认定服务商没有搜索。",
} as const satisfies ProductClaim;

const zhReviewedOpportunities = {
	id: "product-reviewed-opportunities",
	status: "managed-delivery",
	text: "机会建议由运营人员生成，并在交付前经过人工审核。",
	limitation: "Yonaris 不会自主修改内容或代替客户发布。",
} as const satisfies ProductClaim;

const zhHeroWorkspace = {
	id: "product-hero-workspace",
	status: "current-software",
	text: "客户可以在工作区中查看已配置的 Program 与回答证据；",
	limitation: `${zhConfiguredScope.limitation}${zhReviewableEvidence.limitation}`,
} as const satisfies ProductClaim;

const zhHeroOperations = {
	id: "product-hero-operations",
	status: "managed-delivery",
	text: "部分采集及机会建议的审核目前仍由 Yonaris 团队完成。",
	limitation: `${zhConfiguredSampling.limitation}${zhReviewedOpportunities.limitation}`,
} as const satisfies ProductClaim;

const zhCoverage = {
	id: "product-configured-coverage",
	status: "current-software",
	text: "覆盖范围取决于 Program 中配置的服务商与消费端界面。",
	limitation: "部分界面不会公开引用或搜索查询；字段不可用不能证明没有发生搜索。",
} as const satisfies ProductClaim;

const zhIllustrativeScope = {
	id: "product-illustrative-scope",
	status: "illustrative",
	text: "工作台中的范围属于虚构的 Northstar Materials 示例。",
	limitation: "其中的公司、Program、市场与跟踪问题均为示例，并非客户数据。",
} as const satisfies ProductClaim;

const zhIllustrativeAnswer = {
	id: "product-illustrative-answer",
	status: "illustrative",
	text: "工作台保留一条完整的虚构回答样本，并标明界面、模型与采样时间。",
	limitation: "这段回答是设计示例，不代表实时服务商回答或产品结果。",
} as const satisfies ProductClaim;

const zhIllustrativeSources = {
	id: "product-illustrative-sources",
	status: "illustrative",
	text: "虚构回答同时展示可检查的引用与明确标为未知的查询状态。",
	limitation: "未知表示该字段未向本次样本公开，不能证明没有发生搜索。",
} as const satisfies ProductClaim;

const zhIllustrativeNextTest = {
	id: "product-illustrative-next-test",
	status: "illustrative",
	text: "虚构记录以一项边界清晰的下一步测试和明确的人工审核责任人收尾。",
	limitation: "下一步测试是可审核的假设，不是自动执行的动作，也不是因果结论。",
} as const satisfies ProductClaim;

export const pageZh = {
	meta: {
		title: "让 AI 形成的市场答案变得可观察",
		description: "先界定市场范围，再检查 AI 回答样本及其可用证据，最后选择一个边界清晰的下一步测试。",
	},
	eyebrow: "产品 · 证据工作台",
	headline: "让 AI 形成的市场答案变得可观察",
	currentScope:
		"客户可以在工作区中查看已配置的 Program 与回答证据；部分采集及机会建议的审核目前仍由 Yonaris 团队完成。",
	heroClaims: [zhHeroWorkspace, zhHeroOperations],
	heroClaimSeparator: "",
	activitiesLabel: "一条证据工作流",
	activitiesTitle: "四项活动，串成一条范围明确的证据链。",
	boundaryLabel: "产品边界",
	contextLabel: "产品与应用场景",
	workspaceBoundary: {
		title: "现阶段的工作边界",
		customer: {
			title: "客户工作区",
			claims: [zhConfiguredScope, zhReviewableEvidence],
		},
		yonaris: {
			title: "Yonaris 执行",
			claims: [zhConfiguredSampling, zhReviewedOpportunities],
		},
	},
	coverage: {
		title: "覆盖范围需要声明，不能想当然",
		claims: [zhCoverage],
	},
	activities: [
		{
			id: "define-scope",
			title: "界定范围",
			summary: zhConfiguredScope.text,
			claims: [zhConfiguredScope],
		},
		{
			id: "observe-answer",
			title: "观察回答",
			summary: zhConfiguredSampling.text,
			claims: [zhConfiguredSampling],
		},
		{
			id: "inspect-evidence",
			title: "检查证据",
			summary: zhReviewableEvidence.text,
			claims: [zhReviewableEvidence],
		},
		{
			id: "choose-next-test",
			title: "选择下一项测试",
			summary: zhReviewedOpportunities.text,
			claims: [zhReviewedOpportunities],
		},
	],
	workbench: {
		eyebrow: "虚构 Program · Northstar Materials",
		title: "沿着一条样本，走完从范围到下一项测试。",
		description: "这份示例记录展示证据如何保持可复核，同时明确它不是真实客户数据，也不是实时产品结果。",
		ui: {
			tabListLabel: "示例证据视图",
			capabilityContextLabel: "能力说明",
			illustrativeLabel: "示例",
			knownLabel: "已知",
			unknownLabel: "未知",
			currentSoftwareLabel: "当前软件能力",
			managedDeliveryLabel: "团队交付",
			verifiedEvidenceLabel: "已核验证据",
			directionLabel: "方向",
		},
		views: [
			{
				id: "scope",
				tabLabel: "范围",
				title: "范围明确的 Program",
				description: "样本从审核者真正希望观察的市场与问题开始。",
				status: "illustrative",
				claims: [zhIllustrativeScope, zhConfiguredScope],
				fields: [
					{ label: "品牌", state: "known", value: "Northstar Materials · 虚构公司" },
					{ label: "市场", state: "known", value: "美国库存规划软件" },
					{ label: "语言", state: "known", value: "英语" },
					{ label: "时区", state: "known", value: "America/New_York" },
					{ label: "跟踪问题", state: "known", value: "哪些库存规划平台最适合区域制造企业？" },
				],
			},
			{
				id: "answer",
				tabLabel: "回答",
				title: "一条完整的虚构回答",
				description: "回答始终与示例使用的界面、模型标签及观察时间保持关联。",
				status: "illustrative",
				claims: [zhIllustrativeAnswer, zhConfiguredSampling],
				fields: [
					{ label: "界面", state: "known", value: "Atlas Answer · 虚构消费端界面" },
					{ label: "模型", state: "known", value: "Atlas Preview 2 · 虚构模型" },
					{ label: "采样时间", state: "known", value: "2026 年 8 月 14 日 · 14:30 UTC · 示例" },
					{
						label: "完整回答样本",
						state: "known",
						value:
							"面向区域制造企业，可以比较擅长情景规划的 Northstar Materials、侧重供应商协作的 Quarryline，以及聚焦需求预测的 Ledgerfield。选型前还需核实数据覆盖与实施支持。",
					},
				],
			},
			{
				id: "sources",
				tabLabel: "来源",
				title: "既呈现证据，也保留未知",
				description: "已知来源字段与不可用的查询证据始终是两种不同状态。",
				status: "illustrative",
				claims: [zhIllustrativeSources, zhReviewableEvidence],
				fields: [
					{
						label: "引用 01",
						state: "known",
						value: "区域制造企业的库存情景分析 · northstar.example · 虚构",
					},
					{
						label: "引用 02",
						state: "known",
						value: "规划平台评估指南 · fieldmanual.example · 虚构",
					},
					{
						label: "公开的搜索查询",
						state: "unknown",
						reason: "这个示例界面没有向采样器公开查询字段；这不能证明没有发生搜索。",
					},
				],
			},
			{
				id: "next-test",
				tabLabel: "下一项测试",
				title: "边界清晰、经过人工审核的下一项测试",
				description: "记录以一项可复测的内容调整收尾，而不是自动运行的建议闭环。",
				status: "illustrative",
				claims: [zhIllustrativeNextTest, zhReviewedOpportunities],
				fields: [
					{
						label: "观察到的缺口",
						state: "known",
						value: "回答提到了 Northstar，却没有说明其区域 ERP 连接器的边界。",
					},
					{
						label: "下一项边界测试",
						state: "known",
						value: "在一个对比页面中澄清连接器边界，再重复同一组已声明的问题。",
					},
					{ label: "人工审核", state: "known", value: "Yonaris 分析师 + 客户市场负责人" },
					{
						label: "因果影响",
						state: "unknown",
						reason: "需要重复观察同一组样本；单条示例不能得出因果结论。",
					},
				],
			},
		],
	},
	contextLinks: {
		title: "把证据模型用于真实问题",
		geoLabel: "查看 GEO 工作流程",
		diagnosticLabel: "获取免费诊断",
	},
	homePreview: {
		title: "从回答样本回到可复核证据",
		summary: zhReviewableEvidence.text,
		evidenceLabel: "示例证据视图",
		limitation: zhReviewableEvidence.limitation,
		claims: [zhReviewableEvidence, zhCoverage],
	},
	claims: [zhConfiguredScope, zhConfiguredSampling, zhReviewableEvidence, zhReviewedOpportunities],
	limitations: [
		"完整流程尚未开放自助注册与执行。",
		"样本反映的是特定范围内的观察，不等同于因果归因、排名保证或全量覆盖。",
	],
} as const satisfies ProductContent;

export const productContentByLocale: DeepReadonly<Record<Locale, ProductContent>> = deepFreeze({
	en: pageEn,
	zh: pageZh,
});

export function getProductContent(locale: Locale): DeepReadonly<ProductContent> {
	return productContentByLocale[locale];
}
