import type { PageMeta } from "./global";
import type { FactualClaim, Locale } from "./types";

export interface ProductActivity {
	id: string;
	title: string;
	description: string;
	operation: string;
}

export interface ProductContent {
	meta: PageMeta;
	eyebrow: string;
	currentScope: string;
	workspaceBoundary: { customer: string; yonaris: string };
	activities: readonly ProductActivity[];
	coverageDisclosure: string;
	claims: readonly FactualClaim[];
	limitations: readonly string[];
}

export const pageEn = {
	meta: {
		title: "Make AI market answers observable.",
		description:
			"Define a market scope, inspect sampled AI answers and their available evidence, then choose a bounded next test.",
	},
	eyebrow: "Evidence workbench",
	currentScope:
		"The customer workspace exposes configured Programs and reviewable answer evidence; Yonaris currently operates some collection and reviews opportunity recommendations.",
	workspaceBoundary: {
		customer:
			"Customer workspace: define and inspect Programs, tracked questions, metrics, individual responses, and available evidence.",
		yonaris:
			"Yonaris-operated execution: configure supported collection, run managed consumer-surface workflows, and review evidence-grounded opportunities.",
	},
	activities: [
		{
			id: "define-scope",
			title: "Define the scope",
			description:
				"Set brand identity, competitor cohort, market, language, timezone, and tracked questions for one Program.",
			operation: "Customer-visible configuration",
		},
		{
			id: "observe-answer",
			title: "Observe the answer",
			description: "Collect repeated samples through configured providers and managed consumer-surface workflows.",
			operation: "Software plus managed delivery",
		},
		{
			id: "inspect-evidence",
			title: "Inspect the evidence",
			description:
				"Review mention rate, configured-cohort share of voice, exact responses, citations, and exposed query rewrites.",
			operation: "Customer-visible evidence",
		},
		{
			id: "choose-next-test",
			title: "Choose the next test",
			description: "Turn observed gaps into evidence-grounded opportunities that a person reviews before action.",
			operation: "Yonaris-reviewed recommendation",
		},
	],
	coverageDisclosure:
		"Coverage depends on the configured Program. Some surfaces do not expose citations or search queries, and their absence does not establish that no search occurred.",
	claims: [
		{
			id: "product-configured-scope",
			status: "current-software",
			text: "Workspaces support brand, domain, alias, competitor, Program, and tracked-question configuration.",
			limitation: "Scope is configured per Program rather than inferred as universal market coverage.",
		},
		{
			id: "product-configured-sampling",
			status: "managed-delivery",
			text: "Yonaris collects configured provider samples and can operate supported consumer-surface collection.",
			limitation: "Some execution remains operator-managed and is not continuous or universally available.",
		},
		{
			id: "product-reviewable-evidence",
			status: "current-software",
			text: "Users can inspect sampled responses, mention metrics, configured-cohort share of voice, citations, and exposed query fan-out when available.",
			limitation:
				"A missing citation or query field describes unavailable evidence, not proof that a provider performed no search.",
		},
		{
			id: "product-reviewed-opportunities",
			status: "managed-delivery",
			text: "Opportunity recommendations are generated by operators and reviewed by people before delivery.",
			limitation: "Yonaris does not autonomously remediate or publish changes.",
		},
	],
	limitations: [
		"The complete workflow is not yet public self-service onboarding.",
		"Results are sampled observations, not causal attribution, ranking guarantees, or universal coverage.",
	],
} as const satisfies ProductContent;

export const pageZh = {
	meta: {
		title: "让 AI 市场回答变得可观察。",
		description: "先界定市场范围，再检查 AI 回答样本及其可用证据，最后选择一个边界清晰的下一步测试。",
	},
	eyebrow: "证据工作台",
	currentScope:
		"客户可以在工作区中查看已配置的 Program 与回答证据；部分采集及机会建议的审核目前仍由 Yonaris 团队完成。",
	workspaceBoundary: {
		customer: "客户工作区：设置并检查 Program、跟踪问题、指标、逐条回答与现有证据。",
		yonaris: "Yonaris 执行：配置受支持的采集方式、运行需要团队操作的消费端界面流程，并审核基于证据的机会建议。",
	},
	activities: [
		{
			id: "define-scope",
			title: "界定范围",
			description: "为一个 Program 明确品牌身份、竞品集合、市场、语言、时区和跟踪问题。",
			operation: "客户可见配置",
		},
		{
			id: "observe-answer",
			title: "观察回答",
			description: "通过已配置的服务商与团队管理的消费端界面流程，重复采集回答样本。",
			operation: "软件与人工交付结合",
		},
		{
			id: "inspect-evidence",
			title: "检查证据",
			description: "查看提及率、指定竞品集合内的声量份额、原始回答、引用及公开的查询改写。",
			operation: "客户可见证据",
		},
		{
			id: "choose-next-test",
			title: "选择下一项测试",
			description: "把观察到的缺口整理成以证据为依据的机会，并在采取行动前由人审核。",
			operation: "Yonaris 审核的建议",
		},
	],
	coverageDisclosure: "覆盖范围取决于 Program 配置。部分界面不公开引用或搜索查询；字段缺失并不能证明没有发生搜索。",
	claims: [
		{
			id: "product-configured-scope",
			status: "current-software",
			text: "工作区支持配置品牌、域名、别名、竞品、Program 和跟踪问题。",
			limitation: "每个 Program 都有明确范围，不代表系统自动覆盖整个市场。",
		},
		{
			id: "product-configured-sampling",
			status: "managed-delivery",
			text: "Yonaris 会采集已配置服务商的样本，也可操作受支持的消费端界面采集流程。",
			limitation: "部分执行依赖运营人员，并非持续运行或适用于所有界面。",
		},
		{
			id: "product-reviewable-evidence",
			status: "current-software",
			text: "用户可以检查回答样本、提及指标、指定竞品集合内的声量份额，以及可用的引用和查询扩展。",
			limitation: "引用或查询字段为空，只表示证据不可用，不能据此认定服务商没有搜索。",
		},
		{
			id: "product-reviewed-opportunities",
			status: "managed-delivery",
			text: "机会建议由运营人员生成，并在交付前经过人工审核。",
			limitation: "Yonaris 不会自主修改内容或代替客户发布。",
		},
	],
	limitations: [
		"完整流程尚未开放自助注册与执行。",
		"样本反映的是特定范围内的观察，不等同于因果归因、排名保证或全量覆盖。",
	],
} as const satisfies ProductContent;

export const productContentByLocale: Readonly<Record<Locale, ProductContent>> = Object.freeze({
	en: pageEn,
	zh: pageZh,
});

export function getProductContent(locale: Locale): ProductContent {
	return productContentByLocale[locale];
}
